### ISSUE TITLE
ExecutionException in AbstractVehicleMission

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#989] opened 2023-08-09 19:13 UTC
**Describe the bug**
- Before departing for a vehicle mission, when preparing for a resource loading plan, the vehicle generates a random list of spare part to bring with it. 
- How should this list be done optimally ? Is it necessary ?

**Expected and unexpected behavior**
- At the minimum, it should not have concurrent issues

**Discuss any potential problems you have and have not ruled out**
- In AbstractVehicvleMission's getSparePartsForTrip() below, the line 
`switch(vehicle.getVehicleType()` triggers `NoClassDefFoundError`
```java
	/**
	 * Gets spare parts for the trip.
	 *
	 * @param distance the distance of the trip.
	 * @return map of part resources and their number.
	 */
	protected Map<Integer, Number> getSparePartsForTrip(double distance) {
		// Determine vehicle parts. only if there is a change of distance

		// If the distance is the same as last time then use the cached value
		if ((cachedDistance == distance) && (cachedParts != null)) {
			return cachedParts;
		}

		Map<Integer, Number> result = new HashMap<>();
		cachedParts = result;
		cachedDistance = distance;

		double drivingTime = getEstimatedTripTime(true, distance);
		double numberAccidents = drivingTime * OperateVehicle.BASE_ACCIDENT_CHANCE;
		double numberMalfunctions = numberAccidents * AVERAGE_NUM_MALFUNCTION;

		Map<Integer, Double> parts = vehicle.getMalfunctionManager().getRepairPartProbabilities();

		// Note: need to figure out why a mission vehicle's scope would contain 
		// the following unneeded parts that must be removed:
		parts = ItemResourceUtil.removePartMap(parts, unNeededParts);

		for (Map.Entry<Integer, Double> entry : parts.entrySet()) {
			Integer id = entry.getKey();
			double value = entry.getValue();
			double freq = value * numberMalfunctions * PARTS_NUMBER_MODIFIER;
			int number = (int) Math.round(freq);
			if (number > 0) {
				result.put(id, number);
			}
		}

		// Manually override the number of wheels and battery needed for each mission
		// since the automated process is not reliable
		switch(vehicle.getVehicleType()) {
			case EXPLORER_ROVER:
				result.computeIfAbsent(wheelID, k -> 2);
				break;
			case CARGO_ROVER, TRANSPORT_ROVER:
				result.computeIfAbsent(wheelID, k -> 4);
				break;
			default:
				break;
		}
		
		return result;
	}
```

**Java classes involved**
- `AbstractVehicleMission`

**Stacktrace**
```
01-Adir-01:701.891 (Info) ReviewMissionPlan : [New Plymouth] Jonathan Gonzalez - Grading Regolith Prospecting #15 Plan - Rels: 9, Site: 33.2, Review: 2; Subtotal: 44.2
01-Adir-01:701.891 (Info) ReviewMissionPlan : [New Plymouth] Jonathan Gonzalez - Done reviewing Jane Anderson's Regolith Prospecting #15 mission plan.
01-Adir-01:701.891 (Info) AbstractVehicleMission : [New Seoul] Chongjin - Prepared a loading plan sourced from New Seoul.
01-Adir-01:701.891 (Severe) UnitManager : Problem running the pulse : 
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/mars_sim/msp/core/person/ai/mission/AbstractVehicleMission$1
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.mars_sim.msp.core.UnitManager.runExecutor(UnitManager.java:471)
	at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:382)
	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1409)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:650)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:607)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: org/mars_sim/msp/core/person/ai/mission/AbstractVehicleMission$1
	at org.mars_sim.msp.core.person.ai.mission.AbstractVehicleMission.getSparePartsForTrip(AbstractVehicleMission.java:1053)
	at org.mars_sim.msp.core.person.ai.mission.EVAMission.getSparePartsForTrip(EVAMission.java:278)
	at org.mars_sim.msp.core.person.ai.mission.AbstractVehicleMission.getOptionalResourcesToLoad(AbstractVehicleMission.java:1311)
	at org.mars_sim.msp.core.person.ai.mission.AbstractVehicleMission.prepareLoadingPlan(AbstractVehicleMission.java:315)
	at org.mars_sim.msp.core.person.ai.mission.AbstractVehicleMission.startLoadingPhase(AbstractVehicleMission.java:2001)
	at org.mars_sim.msp.core.person.ai.mission.AbstractVehicleMission.determineNewPhase(AbstractVehicleMission.java:587)
	at org.mars_sim.msp.core.person.ai.mission.EVAMission.determineNewPhase(EVAMission.java:68)
	at org.mars_sim.msp.core.person.ai.mission.AbstractMission.performMission(AbstractMission.java:599)
	at org.mars_sim.msp.core.person.ai.Mind.resumeMission(Mind.java:305)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:285)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:248)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:175)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:118)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:865)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1169)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:905)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:816)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:796)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.mars_sim.msp.core.person.ai.mission.AbstractVehicleMission$1
	... 22 more

01-Adir-01:702.039 (Info) TaskManager : [New Seoul] Yejun Han - Given a pending/appointed task 'Load via EVA @ Regolith Prospecting #3'.
01-Adir-01:702.039 (Info) BuildingManager : [New Seoul] Chongjin - Just stowed inside Garage 1.
01-Adir-01:702.039 (Warning) Task : [New Seoul] Yejun Han - Early end of Loading Vehicle in Garage: Vehicle has no loading plan
01-Adir-01:702.039 (Warning) Unit : Junu Jeong expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Ji-ju Ki expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Chuwon Yu expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Ji-min Jun expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Jian Kang expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Koryo expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Zyle expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Drone 011 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : LUV 010 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : LUV 012 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Chongjin expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Drone 010 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : Drone 012 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : LUV 011 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : DeliveryBot 003 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : MakerBot 009 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : RepairBot 010 expected pulse #4726 but received 4727
01-Adir-01:702.039 (Warning) Unit : GardenBot 012 expected pulse #4726 but received 4727
```

**Specifications (please complete the following information)**
- pre-3.6.0 build 8473

**Additional context**
The following 3 exceptions are generated : 
- `ExecutionException`
- `ClassNotFoundException`
- `NoClassDefFoundError`

**Comment by bevans2000** [comment] 2023-08-09 21:46
This is not a concurrency issue, it is an execution exception because it is thrown from a FutureTask. The root cause is the ClassDefNotFound. Is this a reloaded simulation? It could also be you have a corrupted workspace so your classpath is broken.

**Comment by mokun** [comment] 2023-08-09 21:56
> Is this a reloaded simulation? It could also be you have a corrupted workspace so your classpath is broken.

I don't remember if it's a reloaded sim. 

When I clicked on the first exception, it takes me to the line `vehicle.getVehicleType()` which is probably the one that triggers it. Or it may have been something else.

Say if that's indeed the case, why ?

**Comment by bevans2000** [comment] 2023-08-09 22:12
Well the class it says is not found is an inner class of AbstractVehicleMission. Have you changed anything there. My guess is your workspace has a problem because it looks like it is the lambda code missing the switch statement which is odd. 
I should have some spare time tomorrow after work. Try forcing a clean of your eclipse projects. 
Does it happen all the time? Make a change to the java file to force a recompile of that class

**Comment by mokun** [comment] 2023-08-09 22:35
> an inner class of AbstractVehicleMission. Have you changed anything there. My guess is your workspace has a problem because it looks like it is the lambda code missing the switch statement which is odd.

I was working on the OptimizeSystem task. Never touched any vehicle related class such as  AbstractVehicleMission at all. 

Anyway, if I run into that again, I'll post the update.

**Comment by bevans2000** [comment] 2023-08-18 11:58
Let's close this if you haven't seen it again. It is definitely a missing compilation problem in the environment.

**Closed as completed** 2023-08-18 15:36 UTC
