### ISSUE TITLE
Regolith collection does not work

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#629] opened 2022-07-14 21:58 UTC
**Describe the bug**
- Regolith collection does not work. It collects zero regolith(s) during Regolith Prospecting missions.

**Expected behavior**
- It used to be collecting some types of regoliths. Perhaps it was due to some recent changes that it no longer collects regoliths.

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/179095334-525abfda-684e-4454-a500-08399a6c1f18.png)

**Version**
 - pre-3.4.0 build 6950

**Additional context**
- CollectResourcesMissionCustomInfoPanel class display both the ice and regolith collection.

**Comment by bevans2000** [comment] 2022-07-15 13:09
I'm hunting done this problem and #517. I think the problem relates to not enough time  on site because the original site time calculation was not correct but in the old code it was never actually used. In the new consolidated code it is used and hence EVA site time is cut short.

**Comment by bevans2000** [comment] 2022-07-15 13:21
I've found the problem but will run some more tests.

**Comment by bevans2000** [comment] 2022-07-16 10:01
So I didn't find the definitive root cause of the problem but there was some weird logic around the time on site and the collection rate used. The problem seems to be related to calculating a very low collection rate for the Collection Task coupled with site time being too short. Result was Person started a Collection Task but never actually collected anything.
In this recent commit I have put a fixed maximum time for the EVA phase; this is fine because there is a maximum collected resource value which should be hit first anyway. Secondly the rate passed to the Collection Task comes from teh Person estimate not the Mission estimate which is too low.
Tested it this morning and Missions are collecting resources.
Code needs a bit of a further tidy up as well.

**Comment by mokun** [comment] 2022-07-16 14:41
> The problem seems to be related to calculating a very low collection rate for the Collection Task coupled with site time being too short. 

We could improve how collection rate estimation is done and make it less random and more dependent on meaningful factors.

It makes more sense to adjust this collection rate further by a new task that would spend some "computing resource" in running computer simulation to pinpoint the location better.

We could make it happen in such a way that the more a person asks for computer time, the better the confidence or probability of finding the actual resource. 

However, there will also be "diminishing return" if asking for too much computing simulation.

> Result was Person started a Collection Task but never actually collected anything.

**Comment by mokun** [comment] 2022-07-16 14:46
> Result was Person started a Collection Task but never actually collected anything.

How much actual time a person spent in EVA to mine mineral or collect resources is a mystery.

We could create a personal log to record exactly what a person encounters out there to give us more hint. 

Seems a person still spending time doing scientific study and listening to music or teaching or other things, instead of stepping outside or surveying the environment (even if he's inside the vehicle) ...

**Comment by mokun** [comment] 2022-07-16 15:07
@bevans2000 @Urwumpe 

I imagine a real expedition would include spending a lot of time on instrument/equipment, tweaking, fine-tuning or even hacking them in order to get the job done. 

We'll need to create tasks and meta tasks like that. And possibly having a skill on each type of survey/data collection instrument. 

What do you think ?

**Comment by bevans2000** [comment] 2022-07-16 16:25
First thing first, lets fix the current problems. I've opened a can of worms this afternoon running some tests finding a few long term problems they haven't been noticed. The old logic was weak in ending an EVA phase; it just wait for everyone to return naturally so eventually everyone would be on the Rover.
The new logic is more controlled, correctly so, and it stops any active EVAOperations and gets those Person to return to the vehicle. No new EVAs can start in this time period either.
What I have found is that it's possible for the Vehicle to set-off whilst someone is in the process of leaving the Vehicle via the Airlock, hence they get abandoned. I have commonly seen this situation but never worked out why; now I know...
Secondly there are 2 different ways to calculate if there is enough light for an EVA. One in the Mission code and a different approach in the EVAOperation code. This creates the situation of a Person thinking it is too dark for an EVA whilst the Missions thinks it is OK. This could be the cause of the non-EVA tasks during a Mission. 
Also I do think that the enough sunlight logic maybe too aggressive and EVAs are stopping too soon.
However my current goal is to get all the Resource Collection missions working in a logic pattern and collect some material. It may be that it is not enough because the rate are too low but that is a different Issue.
I'm in the grove now and determined to get to the bottom of these problems once and for all.

**Comment by Urwumpe** [comment] 2022-07-16 17:38
> @bevans2000 @Urwumpe

> We'll need to create tasks and meta tasks to address this aspects of a field trip. And possibly adding new skills to represent how familiar a person is in using each type of survey/data collection instrument.
> 
> What do you think ?

I first of all think its a great idea that could also allow some future growth potential, but we should plan this out a bit more. I believe, we would have more fun there, if we could just define some scientific device in XML and the framework automatically assigns a set of suitable actions for it, that can be used in a scientific project. That way, we could quickly add more tools for more scientific tasks with only little future coding.

Second, @bevans2000 is right, we have to fix the problems in the EVA code first, so we can rely on it in the future.

We could of course also allow some extension to the day/night cycle by allowing the astronauts to use headlights in their EVA suits. Maybe with a small penalty, that would be a matter of balancing. But in the end, if its not darkness that ends the day, its the need for sleep by the settlers. 

And third: What about experimenting with different patterns of EVA plans? Like:

- one 8 hour EVA per day followed by recreation and sleep.
- A three shift EVA for larger projects, requiring at least six astronauts working in 4 hour shifts outside, with one team entering the rover again as the next team leaves the airlock to reduce airlock cycles.
- Laissez-faire, limited by daylight
- etc.

So, if we have a project that contains EVAs, we might have a EVA block encapsulating the activities that have to be done outside, and which has the EVA pattern assigned to it how the EVAs are executed. By having fixed time boxes, we reduce the complexity for the planning and simply have the decision to solve, shall a new task be started, that might exceed the limits of the time box or should it be postponed for the next time box. The end of work would not arrive sudden by sunset, but organized and extending the work into darkness could be an option, as long as it keeps the emergency reserve of oxygen in the EVA suit (enough for entering the rover again)

**Comment by bevans2000** [comment] 2022-07-16 19:53
The latest commit should significantly improve the situation. 
Once we adopt the generic Project model of #625 it will be easier to add generic steps to the mission flow.

**Comment by mokun** [comment] 2022-07-17 01:46
> define some scientific device in XML and the framework automatically assigns a set of suitable actions for it, that can be used in a scientific project.

I suppose we can associate certain instruments to a type of mission or a type of scientific work to be conducted.

Currently, we have the following 7 instruments defined as 'parts'. 

![image](https://user-images.githubusercontent.com/1168584/179380380-2f26d6aa-bef8-4cbd-ac92-ccc425a39b8b.png)

But we haven't done anything with them since we haven't defined what purpose each instrument would serve and how.

I'm sure in real world we'll need a lot more other instruments but at least it serves as a springboard for our discussion here or in a separate thread.

Depending on the complexity of modeling, may be we'll need them to be an Equipment object and not just a simple Part that are not distinguishable from others.

**Comment by mokun** [comment] 2022-07-17 01:48
> The latest commit should significantly improve the situation.

Yes I can see they start collecting resources quite well for now.

**Closed** 2022-07-17 10:39 UTC
Labels: bug

**Comment by Urwumpe** [comment] 2022-07-17 15:27
Can we talk about the scientific instrument feature idea in a new issue? Just for keeping things a bit less chaotic and for defining what is needed to go on. 

I also have another question regarding the Equipment class, maybe we can talk about this in gitter?

**Comment by bevans2000** [comment] 2022-07-17 17:42
@Urwumpe yes create a new Issue for the instrument change.

**Comment by mokun** [comment] 2022-07-17 19:32
> Can we talk about the scientific instrument feature idea in a new issue? Just for keeping things a bit less chaotic and for defining what is needed to go on.

Sure !

> I also have another question regarding the Equipment class, maybe we can talk about this in gitter?

I'm good either way
