### ISSUE TITLE
Unable to open Lander Hab's building unit window

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1371] opened 2024-08-20 05:12 UTC
**Describe the bug**
- For any Phase 0 or Phase 1 settlement templates, the Lander Hab's building unit window cannot be opened.
- This only affects Phase 0 or Phase 1 settlement templates

**Java classes involved**
- `BuildingUnitWIndow`

**To Reproduce (Please provide steps)**
- Steps to reproduce the behavior:
1. Go to Settlement Map
3. Right click on the Lander Hab building
4. Choose "Detail" on the pop up menu
5. Unable to open the building unit window of this Lander Hab

**Stacktrace**
-None

**Specifications**
- pre-3.8.0

**Comment by mokun** [comment] 2024-08-20 05:29
@bevans2000 

Can you find out why the reason as to why only Phase 0 and Phase 1's settlement template's Lander Hab building's unit window can't be rendered ?

**Comment by bevans2000** [comment] 2024-08-20 07:07
Yes, assign this to me and I will look at it this week

**Comment by bevans2000** [comment] 2024-08-24 14:44
@mokun I can't reproduce this problem no matter what I try. Did you see it in a specific scenario?
I have cleaned up the selection logic in the Settlement Map window anyway.

**Comment by mokun** [comment] 2024-08-24 16:45
> Did you see it in a specific scenario?

No. It's not a settlement scenario. 

Start an one-settlement Phase 0 or Phase 1 settlement and you'll see that somewhat the unit window for Lander Hab building won't pop open. Don't know why.

**Comment by mokun** [comment] 2024-08-24 20:06
For instance, in this phase 0 settlement, I hover the mouse cursor over the Lander Hab and right click to have the menu pop out. 

Then I choose "Details", no building unit window would pop open. Nothing happens. No stacktrace showing any exceptions at all.

![image](https://github.com/user-attachments/assets/87a9ef0f-8cd2-45e9-a3c6-9aa1d9c5938d)

**Comment by mokun** [comment] 2024-08-24 20:09
Somehow, it only affects Phase 0 or Phase 1 settlement template with one Lander Hab.

For Phase 2 or above, they have more than one Lander Hab. Selecting "Details" would have the building unit window open without any problems.

**Comment by mokun** [comment] 2024-08-24 20:12
Granted that Lander Hab has a lot of Functions and thus having to create a lot of tabs, can we add some codes to catch whatever exceptions in possibly one of its tab ?

**Comment by bevans2000** [comment] 2024-08-25 07:41
Ok, so what settlement template is used in that Settlement New Maktoum? Any other settlement created?

**Comment by mokun** [comment] 2024-08-25 11:02
> Ok, so what settlement template is used in that Settlement New Maktoum? Any other settlement created?

I used this eclipse launcher to load that UAE template for starting that simulation session: 
https://github.com/mars-sim/mars-sim/blob/master/mars-sim-ui%2FMarsProject%20-new%20UAESA%200-AE%20two%20persons.launch

You can use any phase 0 or phase 1 templates and the result can be easily reproduced. 

Somehow the Lander Hab is the only building affected.

**Comment by bevans2000** [comment] 2024-08-25 19:13
Right, took a while but reproduced it. So the problem is in the "remembered" UI locations of previously opened Unit Windows.  You have saved the window of the Lander Hab previously when you had a bigger screen, so when it reopens it is off screen.
I can fix this.

**Closed** 2024-08-25 23:21 UTC
Labels: bug
