### ISSUE TITLE
Rover malfunctions not repaired during mission, Malfunction Modeling, Atmosphere, Vehicle Status

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#194] opened 2019-06-07 22:25 UTC
**Describe the bug/issue**
When a malfunction happens during a mission, it is not repaired despite enough spareparts being around. The rover is in status MALFUNCTION and the settlers are not driving towards the emergency location.  

**Affected Area**
Rover, AI

**Expected behaviors**
If possible, malfunctions should be repaired.
If a malfunction can't be repaired and does not prevent driving to the emergency location, the crew should drive towards the destination. 
If its possible to drive and repair at the same time, 
If it is not possible to continue driving, emergency beacon should be activated. 

Suggestion: Split the malfunction status into substatuses: 

MALFUNCTION: IMMOBILE   

Can't move at all, repairs impossible. Emergency Beacon should be set ASAP.

REPAIRS: IMMOBILE

Can't move as long as repairs are going on. 

MALFUNCTION

Can move while being repaired. 

DANGER

No malfunction left, but life-support resources (oxygen, water, food) are running out. Abort to a rendezvous point for being resupplied by a to-be-created EmergencyRendezvousMission. Activate Emergency Beacon. 

**Actual/Observed Behaviors**
Malfunctions are eternal, emergency beacon is not activated, rover is not driving towards emergency destination.

**Comment by mokun** [comment] 2019-07-01 02:36
> The rover is in status MALFUNCTION and the settlers are not driving towards the emergency location.

It's quite likely that EITHER there are repair **Parts** that are NOT available, OR that no one at that time is "qualified" to fix the malfunction, OR BOTH.

May be we can add some sort of **visual indicators** to show the players what is missing and is awaiting to happen before it can be rectify... if this is the case, do brainstorm a little more here on what to do.

**Comment by mokun** [comment] 2019-07-02 14:44
I'm curious if it was ever shown in the Event Tab that the vehicle has the malfunction. 

We can create a detail external malfunction log (in JSON) during the simulation. Each time a vehicle malfunction, it captures everything known about this particular malfunction incident. 

The `MalfunctionManager` should be improved to do more things such as this.

**Comment by Urwumpe** [comment] 2019-07-03 18:36
> It's quite possible that EITHER there are repair **Parts** that are NOT available, OR that no one at that time is "qualified" to fix the malfunction, OR BOTH.

I can exclude the first case - I checked the repair requirements of both malfunctions on the rover against the available inventory. It is enough spare parts for a few more such malfunctions. 

Not sure how to verify the second case - what qualifies a settler for repairing a malfunction?
> 
> May be we can add some sort of **visual indicators** to show the players what is missing and is awaiting to happen before it can be rectify... if this is the case, do brainstorm a little more here on, say, what to do next.

What about allowing multiple different repairs for a malfunction, including using chewing gum and duct tape for fixing a rover power plant?

**Comment by mokun** [comment] 2019-07-03 19:02
> What about allowing multiple different repairs for a malfunction, including using chewing gum and duct tape for fixing a rover power plant?

Yes. To improve realism, we can implement a few "level" of repairs. 

Some superficial damages can be patched quickly with just a quick fix such as putting a duct tape over a pipe. 

But some require specialized diagnostic equipment in a depot and won't get fix on the road, such as fuel cell stack damage.

**Comment by Urwumpe** [comment] 2019-07-03 19:10
> 
> 
> > What about allowing multiple different repairs for a malfunction, including using chewing gum and duct tape for fixing a rover power plant?
> 
> Yes. To improve realism, we can implement a few "level" of repairs.
> 
> Some superficial damages can be patched quickly with just a quick fix such as putting a duct tape over a pipe.
> 
> But some require specialized diagnostic equipment in a depot and won't get fix on the road, such as fuel cell stack damage.

Yes, and like in Battletech tabletop, you could try repairing a complex component in the field or simply swap it with a new expensive sparepart and let your apprentice do the job. (And of course, you NEVER have the spare part you need).

**Comment by mokun** [comment] 2019-07-04 16:23
>  try repairing a complex component in the field or simply swap it with a new expensive sparepart and let your apprentice do the job. (And of course, you NEVER have the spare part you need).

Sure. The player as the operator of an equipment should be given the choice to 

Either
(1)  be willing to tolerate reduced performance by temporarily patching something 
Or
(2) get back to its full prescribed performance by swapping out the broken part (provided that it has a equivalent field-replaceable part)

At a quick glance on the 39 malfunctions [here](https://github.com/mars-sim/mars-sim/wiki/Malfunctions), I wonder if we could come up with a better scheming. 

e.g. There are 6 different class fires and related can be under "Thermal". Also there are "Electrical", "Mechanical", "Structural", etc.

Fairly recently, we have just added the definition of the 3 types of origins of malfunctions, namely, Part Fatigue, Human Factor and Software Quality Control; but do discuss how we can model better in how we can do a Root Cause Analysis (RCA) and capture that in a malfunction or maintenance JSON log.

**Comment by Urwumpe** [comment] 2019-07-04 22:11
I think those three causes are nice for statistics, but I think they are not helpful for deciding how to repair the malfunction. What is missing is a process of damage control. Just some brainstorming:

Right now, the malfunction already contains the requirements to repair it. One design question now would be, should MSP allow damage control decisions to be wrong? Should a repair always be perfect or could there be partial repairs? 

I would say, any damage control process in MSP should be a chain of different activities. Initially, there should be "first response actions" - putting out fires, closing bulkheads, isolating tanks, etc. Not yet about repairing the damage, but rather preventing the damage to further escalate. 

For such a first step to make sense, malfunctions should be able to escalate. 

Such a first step does not require much intelligence and the current system should be very close to what is needed there.  Maybe we should restrict those malfunctions to be "elemental malfunctions" instead. 

For example. an leak in a hull would not be subject to a complex decision process initially. You would search it and use the single best practise to fix it, because having to decide which repair tool is the best would take life-saving time away. Those malfunctions would have really low skill requirements, since you could assume any settler to have learned how to react in training.

Next, it would be about assessing the damage and extending the durability of the repairs. This would now be a more complex decision and should be restricted to more skilled settlers. Also, I am not sure if this would even be a repeated, iterative process: The settlers keep on assessing the damage and look for better repairs, until either the damage is fixed and/or the emergency ends (for example, disembarking in a base would be enough). 

For allowing a decision process, would we need some kind of definition of impact. 

Also, I would say, this would be easier to implement, if there could be rules that define which malfunctions would be possible for a complex system. In this case, we would not need to define any thinkable malfunction, but just the kind of malfunction possible with a specific atomic component. Also, malfunctions rarely happen to a single component, but usually apply to combinations of components. Gasbags filled with hydrogen are harmless in a Zeppelin, as long as there are no leaks and no ignition sources. 

Soooo, some atomic components should have atomic malfunctions that turn them into the required ingredients for more complex malfunctions, while others always have the required malfunction trait. 

And such atomic malfunctions could maybe have factors that make them more likely to happen for a specific component. For example, a battery could more likel turn into an ignition source and small fire if overheating. Or turning a component off could make sure a malfunction could almost never happen. 

So, we could also describe an task to assess the damage in code in one way as listing which malfunction rules are just one more atomic malfunction away from being invoked (a small hydrazine leak turning into a big fire) and how likely it is too happen (by current knowledge to the settler?).  And a partial repair could be about preventing this single damage more, for example by turning a component off that could be a possible ignition source. 

Of course, it makes no sense for this to be the only impact of a malfunction. turning the life support off might be one option, but it is no solution for the long term. 

Maybe the ERG model could also be adapted into a way to classify repair phases:

- Existence is used for repairs that increase the time that the crew could survive in a rover or a base.
- Relatedness for repairs that make it possible to get help and support (communication, mobility). 
- And Growth finally for being able to continue the mission despite the malfunction.

And similar for classifying malfunctions: An existence threatening malfunction reduces the endurance of the crew. An relatedness threatening malfunction hinders communication and mobility. And a rather harmless mission threatening malfunction could just reduce the ability to continue the mission (eg, less time for collecting rock samples or no longer possible to expand the base)

And another dimension to a malfunction could be time: How long until it has effect? How long will the effect harm? How long until the malfunction would turn from being mere mission threatening to life threatening? And how would a repair change those times?

**Comment by mokun** [comment] 2019-07-05 19:33
> I would say, any damage control process in MSP should be a chain of different activities. Initially, there should be "first response actions" - putting out fires, closing bulkheads, isolating tanks, etc. Not yet about repairing the damage, but rather preventing the damage to further escalate.
> 
> For such a first step to make sense, malfunctions should be able to escalate.

Sure. One way we can code about the impact level of a malfunction : 

* level 1 : minimal - no loss of life, minimal loss of system performance
* level 2 : minor - no loss of life, incurring minor physical injury, minor loss of system performance,
* level 3 : moderate - no loss of life, incurring some physical injury, moderate loss of system performance, 
* level 4 : major -no loss of life, incurring serious physical injury, major reduction of system performance.
* level 5 : castatrophic - loss of life, system inoperable

**Comment by Urwumpe** [comment] 2019-07-05 21:03
How to classify the malfunction, especially how to do so quickly?

For example, what is a "minor physical injury?"

I think it makes sense to have multiple dimensions of the impact:

- medical (crew health)
- mobility 
- communication
- mission


Not sure if a economic dimension makes sense in an emergency, but it might be a factor for deciding how to repair a rover or base if there is no urgency.

**Comment by mokun** [comment] 2019-07-05 21:24
> it makes sense to have multiple dimensions of the impact

Yes I like the dimensions you listed.

> a factor for deciding how to repair a rover or base if there is no urgency.

So far, there are variations of implementation of the repair modeling in mars-sim over an `Item Resources`/`Part`, buildings, vehicles and containers (such as EVA Suit).

But, programmatically speaking, the most basic unit that can be broken, can malfunction and in need of repair is `Part`.

All of them are field-replaceable. The current definition of repair is simply swapping out the broken/malfunctioned part and replaced it with a spare one. 

I'd say ~90% of them can be manufactured on Mars. 10% of them needed to be imported from Earth via *Resupply Tool*.

So if we are going to change this definition of "repair", where do we begin ?

**Comment by Urwumpe** [comment] 2019-07-05 22:11
I could see two directions there to start.

From malfunctions to construction:

1.  Defining an initial list of "malfunction conditions" as a enum. For example "IGNITION_SOURCE" for anything that could be able to ignite a fire.
2. Defining a damage scope. This should contain a set of the currently active malfunction conditions in that scope. A damage scope should be able to be serialized, so it can be saved together with the object.
3. Move the list of malfunctions into a JSON and create POJOs with jackson binding for reading a malfunction definition file.
4. Write a malfunction processor, which takes a damage scope as input and checks which malfunction rules could be triggered. 

From construction to malfunction:
1. Define an engineering bill of materials (EBOM). Every vehicle, building or tool should have a EBOM representing it. This is not using the actual entities in the simulation (like parts), but BOM representations. A EBOM should be simple enough to be directly serialized into JSON, its just data. I would say, it is OK to allow two places for a EBOM to be "hand-written" in JSON: Embedded into a building or rover definition. Or in a separate file containing multiple products.
2. Create assembly parts, which are parts made of other parts. These correspond to BOM assemblies. A leaf in a EBOM could be a specific part or a standard part, which means it is a part or assembly fully conforming a standard. 
3. The root element of a BOM should be the product. This can be rover, building, station or tool, for the current state. 
4. For turning a EBOM into an entity in the simulation, there should be two ways:
5. A quick factory class that takes a EBOM and produces the fitting entity. This could be used for creating the initial simulation state or for resupply missions.
6. A Manufacturing BOM which contains the machines, tools and consumables needed for creating a part or assembly or product and a reference to the EBOM element that it produces. Essentially it would be a expanded version of the [manufacturing.xml](mars-sim-core/src/main/resources/conf/manufacturing.xml)

(As you can see, I am more experience in the BOM world of things than in malfunctions. Its 20 years ago since I worked in IFV maintenance and tank malfunctions are somewhat "different")

A MBOM for a rover would not go down the full way down to each small screw or gasket - it would end at standard components that are usually shipped from Earth. Initially we could even limit those components to EBOMs since we are not intending to manufacture all of them on Mars yet.

Another extension point there could be allowing to introduce hidden manufacturing errors into components produced on Mars.

**Comment by mokun** [comment] 2019-07-06 15:54
> Every vehicle, building or tool should have a EBOM representing it. This is not using the actual entities in the simulation (like parts), but BOM representations. A EBOM should be simple enough to be directly serialized into JSON, its just data.

Yes EBOM is an very interesting idea that we can apply.

Having said that, we may not need to start everything from scratch. 

> Move the list of malfunctions into a JSON and create POJOs with jackson binding for reading a malfunction definition file.

I'm still feeling awkward in using jackson binding for anything.

Can we somehow modify the existing malfunctions definition xml file, namely, [malfunctions.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/malfunctions.xml), to fit our use ?

> Defining a damage scope. This should contain a set of the currently active malfunction conditions in that scope. A damage scope should be able to be serialized, so it can be saved together with the object.

The <system-list> tag in `malfunctions.xml` show a list of systems (or functions of a building) that are susceptible to this malfunction. For instance,

>  			<system name="life support" />
> 			<system name="rover" />
> 			<system name="EVA suit" />
> 			<system name="farming" />

These systems are considered the scopes of what malfunction could affect.

Are they the same as the `damage scope` that you envision ?

**Comment by mokun** [comment] 2019-07-06 16:14
Also, as you can see, some (but not all) `parts` in [parts.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/parts.xml) has a <maintenance-entity-list> tag. 

```
<part name="gasket" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
			<entity name="farming" probability="5" max-number="6" />
			<entity name="living accommodations" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="6" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="2" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
```

That's how we currently translate what part(s) could possibly be damaged by what malfunction via the system scopes being affected.

>      malfunction <---> system scope <---> damage parts

The point is that we may be able to take advantage of some of the work that our predecessors had done and go from there.

**Comment by mokun** [comment] 2019-07-06 16:32
Also, as you can see, some (but not all) `parts` in [parts.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/parts.xml) has a <maintenance-entity-list> tag. 

```
<part name="gasket" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
			<entity name="farming" probability="5" max-number="6" />
			<entity name="living accommodations" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="6" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="2" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
```

That's how we currently track what part(s) need to be looked during routine maintenance

**Comment by mokun** [comment] 2019-07-06 16:59
If we rewind a bit to the beginning of how a malfunction occurs, the way I understand is that there are two different types of Malfunction : 
* Passive Malfunction 
* Active Malfunction 

Passive malfunction is a part of the `Maintenance Modeling`. It's passive because it's just the wear and tear of the system and is **time** based. The wear condition of a building is being tracked in every  frame or so as long as the building is in operation (i.e. in full power mode).

On the other hand, the active malfunction is when a person or a robot is performing a task that involves touching and operating a system (such as EVA Suit).

In this case, the person's personality factor such as `nervousness` as well his skill level could trigger a prescribed malfunction.

So it doesn't fully follow the [Murphy's Law](https://en.wikipedia.org/wiki/Murphy%27s_law) yet :D

**Comment by Urwumpe** [comment] 2019-07-06 17:00
The idea behind a damage scope was close there, essentially I wanted to be able to isolate damage until a malfunction happens that can breach the damage scope and expand beyond it. For example, a fire in one module spreading out to the next. Or quick damage control limiting the damage to one assembly, but that assembly is completely damaged beyond repair then. 

The systems on the other hand as they are now, could still make sense to be used... for a caution and warning system. So, we could still get reports of a farming malfunction, if a component assigned to a farming system fails. 

For keeping things abstract, there should be a general "magic" caution and warning bus system. For a station, such a C&W could be more hierarchical, allowing to locate malfunctions better. When replacing a component that makes use of the C&W, the settlers would need to perform an additional task to tell the component which C&W system is responsible for it. 

Maybe we can put a C&W matrix on the unit information window where it applies (Of course, a bag needs no C&W, a person wearing an EVA suit should have it)

Also there can be a third kind of malfunction: Nature. A meteorite strike for example.

**Comment by Urwumpe** [comment] 2019-07-06 21:29
How is the save game format now planned to be done? XML or JSON? I would prefer to have just one, it would make it much easier to use the same classes then for saving state and defining initial simulation state.

**Comment by mokun** [comment] 2019-07-06 22:34
> How is the save game format now planned to be done? XML or JSON? I would prefer to have just one, it would make it much easier to use the same classes then for saving state and defining initial simulation state.

I haven't looked into that lately. We can discuss more in [#75](https://github.com/mars-sim/mars-sim/issues/75)

**Comment by mokun** [comment] 2019-07-06 22:45
> The idea behind a damage scope was close there, essentially I wanted to be able to isolate damage until a malfunction happens that can breach the damage scope and expand beyond it. 

I see. The concept of `damage scope` is for classifying the extent of the damage. It is realistic and I like it. 

Currently, in health modeling, we have the concept of progressive worsening of health. So if a person has broken bone and if left untreated for a while, it can result in gangrene.  

See [medical.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/medical.xml)

```
		<!-- A broken bone can result in gangrene if left untreated. -->
		<medical-complaint name="Broken Bone">
			<seriousness value="60" />
			<degrade-time value="7.0" />
			<recovery-time value="14.0" />
			<probability value="5.0" />
			<performance-percent value="20.0" />
			<bed-rest-recovery value="true" />
			<treatment-type value="Plaster Cast" />
			<degrade-complaint value="Gangrene" />
		</medical-complaint>
```

Malfunction of a system should do no difference.

**Comment by Urwumpe** [comment] 2019-07-06 22:58
Well, we can observe the following health effects by malfunctions already:

- Suffocation by lack of oxygen
- Lack of water
- lack of food

A few more would also be possible on Mars - Hypothermia for example.

**Comment by mokun** [comment] 2019-08-02 19:10
> For a station, such a C&W could be more hierarchical, allowing to locate malfunctions better. 

What's C&W ?

**Comment by Urwumpe** [comment] 2019-08-02 21:00
"Caution & Warning (System)"  - usually a matrix or array of lights to indicate malfunctions and dangerous situations in a standardized way.  Like the warning lights of a car in the dashboard.  Could also make a good internal API for AI functions, like having event handlers for certain warnings appearing.

**Comment by mokun** [comment] 2019-09-11 00:49
> Suggestion: Split the malfunction status into substatuses:
> MALFUNCTION: IMMOBILE
> Can't move at all, repairs impossible. Emergency Beacon should be set ASAP.
> REPAIRS: IMMOBILE
> Can't move as long as repairs are going on.
> MALFUNCTION
> Can move while being repaired.
> DANGER
> No malfunction left, but life-support resources (oxygen, water, food) are running out. Abort to a rendezvous point for being resupplied by a to-be-created EmergencyRendezvousMission. Activate Emergency Beacon.

Currently, the `StatusType` of a vehicle can be any one of the followings :  

- GARAGED
- MAINTENANCE
- MALFUNCTION
- MOVING
- PARKED
- STUCK
- TOWED 	

It's probably true that only having one of the above status is UNREALISTIC to begin with. 

In reality, there are situations that something is broken and it degrading the performance of a rover but it is still MOVABLE. 

In this case, it should be both MALFUNCTION & MOVING.

**Comment by mokun** [comment] 2019-09-11 02:47
> Not sure how to verify the second case - what qualifies a settler for repairing a malfunction?

It requires sufficient *mechanical* skill.

If a person is too stressful, anxious, hungry or thirsty or sick, his performance would be very low. 

In that case, his *effective* mechanical skill becomes ZERO -- even though his *actual* mechanical skill may be more than 1.

it should only take longer time to repair something.

However, in your case, if no one was repairing it, it may be that `MaintenanceMeta` always calculate the probability as zero.

Or it's simply that the *Repair Parts* are missing.

**Comment by mokun** [comment] 2019-09-11 02:48
> Malfunctions are eternal, emergency beacon is not activated, rover is not driving towards emergency destination.

it probably means something wrong with the beacon.

**Comment by mokun** [comment] 2019-09-11 02:51
> We can create a detail external malfunction log (in JSON) during the simulation. Each time a vehicle malfunction, it captures everything known about this particular malfunction incident.

Since I was suggesting this malfunction log earlier, I'll implement a *vehicle status log* to gain greater insight into what happen to the vehicle for a period of time in the event it happens again.

**Comment by Urwumpe** [comment] 2019-09-11 05:57
Can we see this log in Swing UI or Console then?

**Comment by mokun** [comment] 2019-09-11 06:03
> Can we see this log in Swing UI

Yes it's in now. See the `Log` tab on a vehicle window.

On each vehicle, it makes sense to set the first entry on sol 1 at 000 millisol to *Park*. 

One day when the vehicle is embarked for a trip, it will be set to *Moving* at a certain millisols.

**Comment by mokun** [comment] 2019-09-16 21:29
I've since added a `TabPanelLog` window. Pic attached below.

![TabPanelLog](https://user-images.githubusercontent.com/1168584/64994666-19201780-d88e-11e9-8058-8ddec83369e6.jpg)

In this simulation, Desert Rose rover just suffered from a *Malfunction* at 644 millisol.

**Comment by mokun** [comment] 2019-09-19 22:07
@Urwumpe , 

Another thing is that we have not provided a temperature and air pressure model inside rovers.

Ideally, it should be kept at 34.7 kPa and ~22 deg Celsius, just like in a settlement.

When a malfunction happens to a rover, it may threaten this internal environment as things may go haywire.

The `CompositionOfAir` class calculates and tracks each building in a settlement. 

We'll need to come up with a thinner class to accurately model the air composition in a rover. 

For now, I'll add codes within `Rover` and `Vehicle` class to at least track the current temperature and air pressure if a Rover is on a mission filled with crew members.

**Comment by Urwumpe** [comment] 2019-09-19 22:37
Yeah, I wanted to describe the ambient atmosphere in an enclosed space by a class that includes also moisture and CO2, practically, it makes little sense to use different classes for rovers or space suits from a human inhabitant perspective, they are just smaller volumes.

Any idea how to get this defined for any kind of location?

**Comment by mokun** [comment] 2019-10-24 02:55
Just fixed the malfunctions not being repaired in a vehicle during a mission. Please do test it out.

**Comment by mokun** [comment] 2019-10-26 04:06
@Urwumpe, as you have suggested, 

We will add the ability to manually "trigger" a particular malfunction in a vehicle.

It will be done after player connects to a vehicle and switches to the *Expert Mode* via beryx console by typing **"/e"**.

This way, we can test how well the malfunction repair is being performed :D

**Comment by mokun** [comment] 2019-10-26 15:16
See the snapshot below from the beryx console for manually triggering a malfunction : 

```
-------------------  C O N S O L E   M E N U  -------------------

  1: Connect with MarsNet
  2: Change Autosave Timer
  3: Save the Simulation
  4: Change the Simulation Speed
  5: Set Logging Options
  6: Exit the Simulation
     
Enter your choice: ​1

            << Connection to MarsNet established >>

  ------------------------------------------------------------ 
|      Ctrl + LEFT / RIGHT : scroll through input history      |
|                UP / DOWN : scroll through choices            |
|                       UP : autocomplete your input           |
  ------------------------------------------------------------ 

'/h' : help,  '/k' : keywords,  '/p' : pause/resume,  '/q' : quit

Connected with MarsNet > ​bahram

Bahram : This is Bahram. How can I help?

Connected with Bahram > ​/e


Set Expert Mode to true

Connected with Bahram [Expert Mode] > ​malfunction
  1. Air Leak
  2. Vehicle Fire
  3. Rover Damaged Wheel
  4. Fuel Leak
  5. Generator Problems
  6. Vehicle Power Failure
  7. Communication System Failure
  8. Navigation System Failure
  9. Rover Control Malfunction
 10. Water Leak
 11. Water Contamination
 12. Food Contamination
 13. Electrical Short
 14. Motor Failure
 15. Fuel Pump Failure
 16. LED Lighting Kit Failure
 17. Fuel Cell Stack Failure

Pick a malfunction from above by entering a number :  ​3

Bahram just had 'Rover Damaged Wheel'.

Connected with Bahram [Expert Mode] > ​
```

**Comment by mokun** [comment] 2019-10-26 15:18
The stacktrace/log is as follow : 

```
00-Adir-01:143.480 (Warning) Malfunction : Rover Damaged Wheel - incident #1 - an EVA repair work order was put in place.
00-Adir-01:143.480 (Warning) Malfunction : Rover Damaged Wheel - incident #1 - the repair requires rover wheel (quantity: 1).
00-Adir-01:143.480 (Warning) MalfunctionManager : [New Plymouth] Bahram has Rover Damaged Wheel. Cause : Parts Fatigue.
00-Adir-01:143.480 (Warning) MalfunctionManager :   --- Part : rover wheel ---
00-Adir-01:143.480 (Warning) MalfunctionManager :  (1).   Reliability :    99.999 %  -->  99.903 %
00-Adir-01:143.480 (Warning) MalfunctionManager :  (2).  Failure Rate :     0.001 %  -->  0.068 %
00-Adir-01:143.480 (Warning) MalfunctionManager :  (3).          MTBF :   2007.0 hr  -->  1027.5 hr
00-Adir-01:143.480 (Warning) MalfunctionManager :   --- Malfunction : Rover Damaged Wheel ---
00-Adir-01:143.480 (Warning) MalfunctionManager :  (4).   Probability :       5.0 %  -->  2.534 %
00-Adir-01:145.926 (Info) DigLocalRegolith : [0.0° N 0.0° W] Laura Wilson collected 50.14 kg of regolith outside New Plymouth
00-Adir-01:156.021 (Info) DigLocalRegolith : [0.0° N 0.0° W] Steven Martin collected 50.24 kg of regolith outside New Plymouth
00-Adir-01:156.021 (Info) Malfunction : Rover Damaged Wheel - incident #1 - EVA repair work initiated by Judy Campbell.
00-Adir-01:156.021 (Info) Malfunction : Rover Damaged Wheel - incident #1 - EVA repair work initiated by Samuel Wood.
```

**Comment by mokun** [comment] 2019-10-26 15:23
There are still a few minor things to work on to make it better than it is now.

We could have the commander to put in place a **policy** for repair work -- who to assign to the scene or *how many* settlers should respond to a malfunction. 

Note: there are 3 types of repair work : general, emergency and EVA.

Currently, it's more or less set to pick the one(s) who the best mechanical skill in the affected area. But this is just an arbitrary choice.  :D

**Comment by bevans2000** [comment] 2021-02-09 21:51
I have done some rework on the Malfunctions to separate the attributes of the fix away from the definition of the fault. The latter is now a new class `MalfunctionMeta` that is  immutable and shared by other `Malfunction` objects. These now become a record of an actual problem. The repair work has been made generic so it will be easy to add other types of work activities in the future.
I've got some more minor changes and tests to do but should be ready for a merge next week.

**Comment by bevans2000** [comment] 2021-02-15 22:33
Quick update. I have been testing and fine tuning the new `MalfunctionMeta` approach. During this I have undercovered some unwanted initialisation dependencies between some of the key configuration classes. THis means sometimes the simulation would not reload. I think I have sorted the current batch now but the static references between the main classes may cause a problem again. So I have reworked the `OrbitInfo` & `MarsClock` to simplify their dependencies.

**Comment by mokun** [comment] 2021-02-16 17:13
> THis means sometimes the simulation would not reload... So I have reworked the `OrbitInfo` & `MarsClock` to simplify their dependencies.

@bevans2000 ,

Yes I suppose the new concurrent threading approach that we have adopted recently might have been causing some of the static reference to load out of proper order.

Or it could be something else lurking underneath ?!

Also, the steps of starting from a brand new sim is slightly different from the steps of reloading a saved sim, if we are not careful.

Let's see if there are more of these.

**Comment by bevans2000** [comment] 2021-02-17 21:09
I have committed a large batch of changes that rework the Malfunction area to simplify the dependencies.

**Comment by mokun** [comment] 2021-06-06 07:25
This thread is long and we've discussed and worked on a few things. We should close it now and continue our dialog in the discussion page under a new thread.

**Closed by mokun** 2021-06-06 07:25 UTC
Labels: bug, improvement, need test
