### ISSUE TITLE
Lot of deprecation warnings while compiling the game. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#272] opened 2020-01-14 01:33 UTC
There are lot of warnings which I have shared while compiling the game. Please fix those. It does enable the compilation but I guess it would fail one way or the other while playing the game in the console mode. 
[mars-sim-issue.txt](https://github.com/mars-sim/mars-sim/files/4056867/mars-sim-issue.txt)

This is with r5256

**Comment by bevans2000** [comment] 2021-03-12 09:37
duplicate of #278

**Comment by bevans2000** [comment] 2022-10-03 17:23
duplicate #278

**Closed by bevans2000** 2022-10-03 17:23 UTC
Labels: deprecated
