### ISSUE TITLE
Bug Report Template

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#63] opened 2018-02-14 12:38 UTC
Have a bug-report template so its easier for the team as well as for newbies to check all.

See https://github.com/rg3/youtube-dl/issues/new as an inspiration what sort of template you can make 

See https://help.github.com/articles/creating-an-issue-template-for-your-repository/ for more.

**Comment by mokun** [comment] 2018-02-17 07:13
That's a good idea.


--------------------------------------------
The template would include :

1. Specifications : 
a. build version - e.g. preview 8, 4255, etc.
b. Operating System (OS) - e.g. Windows 7, Ubuntu 15.04, etc.
c. Java version - e.g. JRE 8u151, OpenJDK  8u91 and OpenJFX etc.

2. Expected behavior vs. actual behavior

3. Steps to reproduce the problem

4. Screenshots at the time of crash
a. Related person's activity tab, 
b. Related vehicle windows, 
c. Monitor Tool's People/Vehicle/Mission tab, etc. 

---------------------------------------------

Anything else to add ?

**Comment by mokun** [comment] 2018-04-28 19:02
@shirishag75 @larsnaesbye  , the way I understand is that there are currently at least two obstacles that we'll need to work out. 

(1) Transitioning mars-sim to go beyond Java 8 or OpenJDK 8 requires the changing the codes Project Jigsaw. See http://openjdk.java.net/projects/jigsaw/  This affects both Oracle Java or OpenJDK.

(2) JavaFX is bundled with Oracle Java 8 but not with OpenJDK. Therefore, if someone uses OpenJDK 8, he will need to install OpenJFK separately in his machine. Beginning Java 9, Oracle introduce breaking changes in the import statement that call for JavaFX UI elements. According to Oracle, they want to give away JavaFX to the open source community one day so that its development is faster. 

It looks like we will need to maintain you separate versions of mars-sim, one for supporting the use of Java 8, one for Java 9 and beyond. Do we want that ? 

Also, should we quit using JavaFX UI ?

**Comment by mokun** [comment] 2018-05-24 23:49
For now, I've added the issue template under `Issues/Tickets` in README.md. Closing this issue now.

**Closed by mokun** 2018-05-24 23:49 UTC
