### ISSUE TITLE
Can't operate a vehicle java.null.pointer exception in build r5242, OperateVehicle task, iterate through settlement map

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#261] opened 2019-12-19 01:15 UTC
Got the following java.lang.nullpointerexception, have no idea what triggered it though - 

```
00-Adir-04:432.951 (Severe) OperateVehicle : [Crater Crab] can't retrieve methane. Cannot drive.
java.lang.NullPointerException
at org.mars_sim.msp.core.person.ai.task.OperateVehicle.turnOnBeacon(OperateVehicle.java:296)
at org.mars_sim.msp.core.person.ai.task.OperateVehicle.mobilizeVehicle(OperateVehicle.java:417)
at org.mars_sim.msp.core.person.ai.task.DriveGroundVehicle.mobilizeVehicle(DriveGroundVehicle.java:230)
at org.mars_sim.msp.core.person.ai.task.OperateVehicle.mobilizeVehiclePhase(OperateVehicle.java:269)
at org.mars_sim.msp.core.person.ai.task.OperateVehicle.performMappedPhase(OperateVehicle.jav
at org.mars_sim.msp.core.person.ai.task.DriveGroundVehicle.performMappedPhase(DriveGroundVeh
at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:610)
at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:557)
at org.mars_sim.msp.core.person.ai.task.utils.TaskManager.executeTask(TaskManager.java:466)
at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:240)
at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:148)
at org.mars_sim.msp.core.person.Person.timePassing(Person.java:1007)
at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:2195)
at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1944)
at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:1065)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by mokun** [comment] 2019-12-20 19:05
```
00-Adir-04:432.951 (Severe) OperateVehicle : [Crater Crab] can't retrieve methane. Cannot drive.
java.lang.NullPointerException
at org.mars_sim.msp.core.person.ai.task.OperateVehicle.turnOnBeacon(OperateVehicle.java:296)
at org.mars_sim.msp.core.person.ai.task.OperateVehicle.mobilizeVehicle(OperateVehicle.java:417)
at org.mars_sim.msp.core.person.ai.task.DriveGroundVehicle.mobilizeVehicle(DriveGroundVehicle.java:230)
```

The `mobilizeVehicle()` method in `OperateVehicle` class had been streamlined. 

It should avoid the NPE above.

@Urwumpe,

I was gonna say that for some strange reason, `unitManager.getSettlements()` would return null  from time to time (but not all the time) inside `isSettlementDestination()` at `OperateVehicle`.

It could be a threading issue.

I've since changed how it works in build 5244.

Let's me if you guys still encounter NPE from the `mobilizeVehicle()` method.

**Comment by Urwumpe** [comment] 2019-12-26 13:04
@Urwumpe,
> 
> I was gonna say that for some strange reason, `unitManager.getSettlements()` would return null from time to time (but not all the time) inside `isSettlementDestination()` at `OperateVehicle`.
> 
> It could be a threading issue.

Would be a strange place for a threading issue - should I take a look at this? If it is one, we should maybe invest some time getting the interfaces cleaned up.

**Comment by mokun** [comment] 2019-12-26 16:42
> Would be a strange place for a threading issue - should I take a look at this? 

@Urwumpe ,

It could be a concurrency issue.

I'm not sure why sometimes Map such as lookupSettlement, lookupPerson, etc. were unavailable. 

There may be some **write** operations at the start of the sim. But after the initial setup, there are only **read** operations done on these Maps. 

So, they should be pretty much 100% available. 

> If it is one, we should maybe invest some time getting the interfaces cleaned up.

I don't mean the Swing EDT.

**Comment by Urwumpe** [comment] 2019-12-26 17:29
I rather suspect that we have multiple instances of thoses classes in our runtime environment by the kind of error happening. We could simply place a thread-safe version of Map there to be sure that it isn't cause by threading,

**Comment by Urwumpe** [comment] 2019-12-26 18:53
Looking at the code, would lookupSettlement be null, the result of the function should be an empty ArrayList. So, it does not appear to be caused by the Map itself being null suddenly.

**Comment by mokun** [comment] 2019-12-27 07:58
> Looking at the code, would lookupSettlement be null, the result of the function should be an empty ArrayList. 

@Urwumpe and @shirishag75 ,

I just did a commit to track that.

Let me know if you see the printing of the log statement `lookupSettlement is null` in the stack trace.

**Comment by shirishag75** [comment] 2019-12-27 08:27
@mokun and @Urwumpe just was hit with https://github.com/mars-sim/mars-sim/issues/263 , dunno if it's the same thing you are looking for or different.

**Comment by mokun** [comment] 2020-08-04 05:08
I haven't encountered any issue driving the vehicle. It was fixed. Closing this.

**Closed by mokun** 2020-08-04 05:08 UTC
Labels: bug
