### ISSUE TITLE
Improve ratio of execution to sleep

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#933] opened 2023-06-20 14:53 UTC
**Is your feature request related to a problem? Please describe.**

The simulation runs slow with a low CPU on Swing, 2% with 12 threads, and with Mars Clock showing statistics like 3 ms execution to 113 ms sleep. 

**Describe the solution you desire to see**
Allow setting a timeratio or different again to increase the CPU load, that mars-sim uses. If the UI slows it down, decouple simulation state from UI update, further reducing dependency of marssim-core on marssim-main

**Describe alternatives you've considered**
`-timeratio` flag gets ignored

**Describe the rationale**
Faster simulation speed, more sols per hour.

**Specifications  (please complete the following information):**

 - Major version and build version : 3.5.0

**Comment by bevans2000** [comment] 2023-06-20 16:38
This is due to the changes made as part of #655 . Before this there was a simpler approach heavily influenced by the time ratio. 
@mokun will have to explain the current approach as I haven't really looked at it. But yes, the actual ratio is never close to the desired.

**Comment by mokun** [comment] 2023-06-20 19:39
> The simulation runs slow with a low CPU on Swing, 2% with 12 threads, 

> Allow setting a timeratio or different again to increase the CPU load, that mars-sim uses.

What's Time Ratio do you currently set to ? 

It usually start at 128x but you can click on "+" and "-" on lower left on the status bar on Main Window to adjust it.

**Comment by mokun** [comment] 2023-06-20 19:48
>  If the UI slows it down, decouple simulation state from UI update, further reducing dependency of marssim-core on marssim-main

As we know, mars-sim-main submodule is the entry module or the boot module. 

It no longer has classes for logging, etc. It used to be but Logger class have been moved to mars-sim-core a year or two ago.
 
So we know the Main thread there spring `MainWindow` of mars-sim-ui submodule. It also gives rise to `Simulation`, `SimulationConfig`, `UnitManager`, etc. in mars-sim-core submodule. 

So my question is what's more can we do to optimize further and "decouple simulation state from UI update".

If we adopt some Java game engines out there, we would have FULL CONTROL of UI threads by design but we haven't.

**Comment by mokun** [comment] 2023-06-20 19:49
> -timeratio flag gets ignored

Yes. We can fix that to make this command flag work again at the start of the sim.

**Comment by mokun** [comment] 2023-06-20 19:54
> The simulation runs slow with a low CPU on Swing, 2% with 12 threads, 

@bevans2000 

I wonder in case of machines like yours that have a lot of threads to spare, can we automatically allocate calculate onto the spare threads ? 

Which managers can we let them run on separate threads ?  SurfaceFeatures`, `Orbit` ? 

May be we should consider having the Mineral Map Layer computation done on a separate thread ?

Probably not `MissionManager`, right ?

**Comment by Urwumpe** [comment] 2023-06-20 20:39
Why think in managers, and not in jobs to process in a timePassing step?

**Comment by mokun** [comment] 2023-11-11 05:46
@Urwumpe 

> -timeratio flag gets ignored

it should work. I use it in those eclipse launcher all the time.

Shall we close this thread ?

**Comment by mokun** [comment] 2023-11-17 06:04
@Urwumpe 

I'll close this now.

**Closed by mokun** 2023-11-17 06:04 UTC
Labels: improvement
