### ISSUE TITLE
Many deaths due to "High Fatigue Collapse", contrary to medical reality

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#274] opened 2020-03-17 09:50 UTC
**Describe the bug/issue**
During the simulation, I observed a high number of deaths due to "High Fatigue Collapse"

**Affected Area**
Health conditions

**Expected behaviors**
High fatigue can be an annoying condition, but could never be deadly by itself.  It kills you by other things, like unexpected events reducing your velocity from 100 km/h to zero in a few milliseconds while you are sleeping.

https://en.wikipedia.org/wiki/Fatigue

Physical and mental fatigue should be modelled as separate conditions.

People should be able to have multiple health effects applying to them. Like falling asleep during EVA possibly ending up with hypoxia or even anoxia.

**Actual/Observed Behaviors**
People can die of high fatigue levels alone. 

**Reproduction (optional)**
Just let the simulation run for one hour.

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version : Oracle JDK 13
 - mars-sim build version : 3.10-swing-java11

**Comment by mokun** [comment] 2020-03-23 18:54
What is the most realistic way of simulating the health situation of having high fatigue collapse  ?

I definite agree they shouldn't die by High Fatigue Collapse alone. Though they may die from secondary complications, such as the low body temperature, head trauma, lack of food/water, etc.. 

I thought there is already a "window" of 1 or more day for a person's health condition to degrade to zero. 

During this time period, someone should have spotted that person lying on the floor or in bed, etc. 

We simulate a person requesting medical attention, but I don't think we have codes to cover how a incapacitated person may be taken care of.

**Comment by Urwumpe** [comment] 2020-03-25 23:41
I had found some many messages saying that a bed could not be reserved in the process to the settler death. Maybe some bug in the code there?

I also can't find any code about how to handle incapacitated persons. There should be some emergency task to reserve a infirmary bed for this settler and move him there.

**Comment by mokun** [comment] 2020-03-26 04:04
> I had found some many messages saying that a bed could not be reserved in the process to the settler death. Maybe some bug in the code there?

Yes very likely. it's possible that a person cannot find a viable path to his/her bed.

**Comment by mokun** [comment] 2020-03-26 04:08
> I also can't find any code about how to handle incapacitated persons. There should be some emergency task to reserve a infirmary bed for this settler and move him there.

Not directly. We could probably tweak the [MedicalAssistance](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/task/MedicalAssistance.java) task and [TreatMedicalPatient](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/task/TreatMedicalPatient.java) task or create a brand new task to account for that need.

**Comment by Urwumpe** [comment] 2020-03-30 18:29
Just skimmed over the MedicalAssistance task... we should really get rid of those overly complex constructors, that essentially already perform the task that gets created there, that is never a good design pattern, as such it essentially replaces a static factory method and the task only stores the result of what is really the task.

**Comment by mokun** [comment] 2020-08-11 03:28
@Urwumpe 

> MedicalAssistance task... we should really get rid of those overly complex constructors, that essentially already perform the task that gets created there, that is never a good design pattern, as such it essentially replaces a static factory method and the task only stores the result of what is really the task.

Okay, the steps in the constructor should be run in its meta task to determine if there is a medical need.

If it does, then there should be a list of MedicalAid instance being set up.

`List<MedicalAid> localAids = getNeedyMedicalAids(person);
`

But it looks like MedicalAssistance is never being into actual use. There is no associated MedicalAssistanceMeta class in existence to instantiate it.

This is a shocker to me that we have things getting only half done by past developers.

What we have now for a doctor to treat patient is through [TreatMedicalPatient](
https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/task/TreatMedicalPatient.java).

We could rename `MedicalAssistance` into `AssistMedicalService` and alter a few things and put it into service. 

I imagine that those who are NOT doctors but have good medical skill could definitely execute this task to help out the real medical staff.

**Comment by mokun** [comment] 2020-08-11 18:12
@Urwumpe 

> that is never a good design pattern, as such it essentially replaces a static factory method and the task only stores the result of what is really the task.

Now, do you mean there is a value in switching to using static factory method to instantiating this task or more ?

**Comment by mokun** [comment] 2020-08-11 18:16
It does sound like a lot of waste if, say, we have 1000 settlers, each settler is doing a task would need to create an object for that and a moment later, that object would be destroyed after it's done.

What is the better alternative that may work in our case ?

**Comment by mokun** [comment] 2020-10-07 06:49
@Urwumpe @jbosmans 
> we should really get rid of those overly complex constructors

Yes I'm looking into simplifying the codes inside the constructor of all of those Task's class. e.g. a new instance of the class `Sleep` is created each time a person picks its corresponding `SleepMeta` as the winner.

So how would you spend the least amount of effort in modifying the codes in such a way that when a person performs a task, there's no need of creating an instance of an object and simply call up a few methods ?

**Comment by jbosmans** [comment] 2020-10-07 07:18
The problem isn't really the creation of object instances, that's been pretty cheap for quite a while performance-wise. 

The issue more likely is a combination of factors:

1. constructors do more than creating an object instance. Both constructors for Sleep (for robot Person and Robot args) have behavior in the constructor. This means simply creating an instance of the Sleep class does more than binding the state to fields. 
2. deep inheritance hierarchies make object construction complex and more expensive. A better way would be depend on interfaces which would enable shared behavior without dictating how things that expose that behavior are implemented. 

Some recommendations worth looking into on those two items:
- execute the behavior that's currently in the constructor before (and pass in the result) or after (and pass any needed input to the method) creating an instance of the respective class. Constructors are about constructing instances, not behavior.
- identify some first candidates for flattening the inheritance hierarchy. Must a person extend the Person class? Or can it be anything that implements eg. the "Human" interface. Both will enable shared operations but the latter allows totally different implementation (and thus doesn't require extending a Person instance)
- when leveraging interfaces it's possible to write generic methods that only accept instances that implement multiple interfaces. Eg. 
`
public <T extends Vehicle & HasWheels> void checkWheels(T vehicleWithWheels);
`
This is not possible with abstract classes since there can only be one super class.
- any work at this level will need to be approached gradually: refactoring with a focus on keeping things working as expected
- lots of mutable state (aka non-final fields in classes) can make things very complex. Take eg. BigDecimal. The implementation is final so adding up 2 BigDecimals doesn't modify any instance state; it returns a new (immutable) instance with the result. 

Just a few thoughts, any work in this area is going to be a voyage of sorts rather than a quick fix

**Comment by mokun** [comment] 2020-10-08 04:35
@jbosmans 
> identify some first candidates for flattening the inheritance hierarchy.

Yes. The `Unit` class is the one that has been extended the most. For instances, `Structure`, `Settlement`, `Building`, `Person`, `Robot`, `Vehicle`, `Rover` all came from it.

Let's see how we'll simplify that

**Comment by mokun** [comment] 2020-10-08 04:43
@jbosmans 

> lots of mutable state (aka non-final fields in classes) can make things very complex. 

Yes. Currently, class such as `Settlement`, `Building`, `Person`, etc. tends to have mutable data produced and handled.

How do we do less in these objects ? 

I do see that extra care is needed to handle these mutable states or else it will cause multi-threading issues. 

So it's better we minimize mutating states.

**Comment by mokun** [comment] 2021-08-20 03:11
@bevans2000 ,

I've disabled the use of High Fatigue Collapse a few month ago since it's buggy.

Guess we can work on bringing it back in a useful manner.

**Comment by mokun** [comment] 2022-10-23 18:26
@bevans2000 @Urwumpe 


For now, no settlers will have have high fatigue collapse since we've disabled it. 

Unless you disagree, we'll postpone the refinement and improvement on medical modeling until later

**Comment by bevans2000** [comment] 2022-10-23 18:46
Let's close it

**Comment by mokun** [comment] 2023-11-11 06:02
@bevans2000 

I agree what you said in another thread that handling of Starvation, Hunger, High Fatigue Collapse and Radiation sickness should be done within the HealthProblem or Complaint class and NOT in PhysicalCondition. 

Will you be able to move the codes to HealthProblem or the way you see as the most fitting solution ?

**Comment by mokun** [comment] 2023-11-11 06:05
@Urwumpe 

> Physical and mental fatigue should be modelled as separate condition

Yes that's true. 

I'm planning to work on [this](https://github.com/mars-sim/mars-sim/issues/1110) and it will touch upon this mental vs. physical therapy issue with possibly better solutions.

Stay tune !

**Comment by bevans2000** [comment] 2023-11-11 06:59
> @bevans2000
> 
> I agree what you said in another thread that handling of Starvation, Hunger, High Fatigue Collapse and Radiation sickness should be done within the HealthProblem or Complaint class and NOT in PhysicalCondition.
> 
> Will you be able to move the codes to HealthProblem or the way you see as the most fitting solution ?

Yes, let's pick this up in 3.8

**Comment by bevans2000** [comment] 2024-06-08 21:16
We need to create UnitTest for the healing Tasks first as part of #1285 before making this change. I can see lots of alterations but we need a UnitTest first.

**Comment by mokun** [comment] 2024-06-09 01:16
> We need to create UnitTest for the healing Tasks first as part of https://github.com/mars-sim/mars-sim/issues/1285 before making this change.

Sure ! I suppose we need unit test on all tasks.

**Comment by bevans2000** [comment] 2024-06-09 06:19
Yes we do. Tasks have a lot of complex logic and they are too difficult to test insitu. I have created a lot recently

**Closed** 2024-06-29 20:39 UTC
Labels: bug
