### ISSUE TITLE
java.lang.NullPointerException in ConstructionManagerTest while trying to compile r5060

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#230] opened 2019-09-28 13:33 UTC
I get the following - 

```
[INFO] Running org.mars_sim.msp.core.structure.construction.ConstructionManagerTest
Sep 28, 2019 6:57:49 PM org.mars_sim.msp.core.mars.RandomMineralMap determineMineralConcentrations
SEVERE: Error creating random mineral map.
java.lang.NullPointerException
	at org.mars_sim.msp.core.mars.MineralMapConfig.getMineralTypes(MineralMapConfig.java:47)
	at org.mars_sim.msp.core.mars.RandomMineralMap.determineMineralConcentrations(RandomMineralMap.java:94)
	at org.mars_sim.msp.core.mars.RandomMineralMap.<init>(RandomMineralMap.java:79)
	at org.mars_sim.msp.core.mars.SurfaceFeatures.<init>(SurfaceFeatures.java:98)
	at org.mars_sim.msp.core.mars.Mars.<init>(Mars.java:43)
	at org.mars_sim.msp.core.Simulation.testRun(Simulation.java:405)
	at org.mars_sim.msp.core.structure.construction.ConstructionManagerTest.setUp(ConstructionManagerTest.java:30)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

java.lang.NullPointerException
	at org.mars_sim.msp.core.mars.MineralMapConfig.getMineralTypes(MineralMapConfig.java:47)
	at org.mars_sim.msp.core.mars.RandomMineralMap.determineMineralConcentrations(RandomMineralMap.java:94)
	at org.mars_sim.msp.core.mars.RandomMineralMap.<init>(RandomMineralMap.java:79)
	at org.mars_sim.msp.core.mars.SurfaceFeatures.<init>(SurfaceFeatures.java:98)
	at org.mars_sim.msp.core.mars.Mars.<init>(Mars.java:43)
	at org.mars_sim.msp.core.Simulation.testRun(Simulation.java:405)
	at org.mars_sim.msp.core.structure.construction.ConstructionManagerTest.setUp(ConstructionManagerTest.java:30)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
Eventually it does build but am concerned about the findings above.

**Comment by mokun** [comment] 2019-09-29 03:57
It's very strange that now `MineralMapConfig` is having issues. 

We'll need to find the root cause as to why so many tests failed if we run them all at the same time. 

But if we run them individually one by one. They will pass.

**Comment by shirishag75** [comment] 2019-09-29 14:52
> It's very strange that now `MineralMapConfig` is having issues.
> 
> We'll need to find the root cause as to why so many tests failed if we run them all at the same time.
> 
> But if we run them individually one by one. They will pass.

I am game with that but no idea. Lemme know what do you want me to try out and will do that.

**Comment by mokun** [comment] 2019-11-27 22:12
We no longer have any issues with ConstructionManagerTest. Close this now.

**Closed by mokun** 2019-11-27 22:12 UTC
Labels: maven test
