### ISSUE TITLE
NPE when assisting scientific study. 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#772] opened 2022-12-08 16:07 UTC
**Describe the bug**
- Need to avoid NPE when assisting scientific study.
- is it possible to use SettlementTask for proposing and assisting scientific research ? 

**Java classes involved**
In `AssistScientificStudyResearcherMeta` L58, we have 
```
   @Override
    public double getProbability(Person person) {

        double result = 0D;
        
        // Probability affected by the person's stress and fatigue.
        if (!person.getPhysicalCondition().isFitByLevel(1000, 70, 1000)) {
        	return 0;
        }
        
        if (person.isInside()) {
	        // Find potential researchers.
	        Collection<Person> potentialResearchers = AssistScientificStudyResearcher.getBestResearchers(person);
	        int size = potentialResearchers.size();
	        if (size == 0)
	        	return 0;
```

The `getBestResearchers` calls up L138 in the `AssistScientificStudyResearcher` class, which in turns calls up L221 and then calls up `PerformLaboratoryResearch`'s getResarchScience().

In `PerformLaboratoryResearch`'s getResarchScience(), it has the following : 
```
	@Override
	public ScienceType getResearchScience() {
		return study.getScience();
	}
```
Note that the study instance above is null since it is not being determined until the meta task is selected 

**Stacktrace**
```
01-Adir-08:061.570 (Severe) UnitManager$SettlementTask : Problem with pulse on Starcity: null
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.PerformLaboratoryResearch.getResearchScience(PerformLaboratoryResearch.java:468)
	at org.mars_sim.msp.core.person.ai.task.AssistScientificStudyResearcher.getAvailableResearchers(AssistScientificStudyResearcher.java:221)
	at org.mars_sim.msp.core.person.ai.task.AssistScientificStudyResearcher.getBestResearchers(AssistScientificStudyResearcher.java:138)
	at org.mars_sim.msp.core.person.ai.task.meta.AssistScientificStudyResearcherMeta.getProbability(AssistScientificStudyResearcherMeta.java:58)
	at org.mars_sim.msp.core.person.ai.task.util.FactoryMetaTask.getTaskJobs(FactoryMetaTask.java:81)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:151)
	at org.mars_sim.msp.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:502)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.startNewTask(PersonTaskManager.java:249)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:306)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:249)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:176)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:119)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:869)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1093)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:976)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:928)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:743)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:723)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Specifications  (please complete the following information):**
 - pre-3.5.0 build 7708

**Comment by mokun** [comment] 2022-12-08 16:11
@bevans2000 

Can the new SettlementMetaTask pattern be used for saving the scientific study instance for proposing and assisting scientific research ?

**Comment by bevans2000** [comment] 2022-12-08 17:32
My reading of the problem is a little different. The ```PerformLaboratoryResearch``` class is a Task object assigned to a different Worker; the Person calling the MetaTask is actually looking for other researcher already doing a Research Task. It should not be possible for the study to be null in a valid Research Task. So my guess is the Task is in the process of being completed by the other Researcher and this Meta Task is hitting that researcher at that time. 
The Research process is one of the few areas that transgresses Settlement boundaries so there is always the risk of concurrent modifications, i.e. the Person making the request could be in a different Thread that the Researcher being checked. Where you running a large number of Settlements?

On the other question I don't think it's suitable to ```SettlementTask``` because the decision to help other Reseachers is not a Settlement type choice.
However, I do think that we can change how a Person assesses whether to join a research study. Instead of the invitee having to go through the MetaTask approach; the inviter could add a dedicated ```JobTask``` instance to respond to the invite directly on the Person's TaskManager. This would be similar to the  Pending Task but would you expect someone to respond to a Research Request immediately which is how the Pending Task approach would go.

**Comment by bevans2000** [comment] 2022-12-08 17:36
Also this is another example where the ```destroy``` methods can leave an object in an inconsistent state.

**Comment by mokun** [comment] 2022-12-08 20:11
> Where you running a large number of Settlements?

Yes my default simulation has 11 settlements. 

Okay. So it could be a threading issue

**Comment by bevans2000** [comment] 2022-12-08 20:16
I suspect it relates to the destroy method clearing down the study attribute before the Task is detached from the Person.

**Comment by mokun** [comment] 2022-12-08 20:21
So do you think it handles the concurrency properly ?

May be the study instance is indeed NOT null in the thread where it was created. 

But because it's not sync, the study instance is null in another thread that reads this thread.

**Comment by bevans2000** [comment] 2022-12-09 21:58
What's interesting is in the ```PerformLaboratoryResearch'`` class the study attribute is never nullified so the Task must not correctly initialise. So I have made a change to check the Task is not done before selecting a researcher. Also made a change to the getLocalPeople method to use the equals method instead of an equality check. In theory it shouldn't matter but it is correct to use equals for objects.

**Comment by bevans2000** [comment] 2023-03-08 22:27
Still a problem?

**Closed** 2023-04-02 06:06 UTC
Labels: bug
