### ISSUE TITLE
Mission shown as "Completed" but with issues, Vehicle Status Log, Flipping garages

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#595] opened 2022-06-16 19:59 UTC
**Describe the bug**
- This Regolith Prospecting mission seems to have been completed.
- It went inside a garage to get things loaded.
- It was reported that a person could not go into this vehicle because it was full : ` Could not enter Martian Cloud. Already full`
- It seems to have departed but went back
- It began unloading
- The vehicle log doesn't show the rover was moving
- The mission tab in monitor tool doesn't show the distance traveled

**Expected behavior**
This mission should be aborted.

**Screenshots**
1. The pic below shows that the mission was "completed"
![image](https://user-images.githubusercontent.com/1168584/174153484-b11c81a2-7e49-4b3d-93ac-64e84ca05d05.png)

2. The pic below shows the vehicle used to go inside garage 1 at sol 1:384 and left outside at sol 1:425. 
![image](https://user-images.githubusercontent.com/1168584/174154389-36719c4d-a5d6-4a20-9a59-c6e453d9bf86.png)

**Desktop (please complete the following information):**
 - pre-3.4.0 build r6786

**Additional context**
1. The stack trace below shows the rover did take off and left the settlement. 
2. It was `Milana Kask - Took the wheel of the rover.` 
3. It went to [0.06 S 0.00 W].
4. Somehow it was aborted but it wasn't reported. 
5. 0.06 S was very close to 0.00 S and may have been mathematically considered as the same location.

```
00-Adir-01:344.667 (Info) MissionManager : [Schiaparelli Point] Julen Gómez - Mission Ice Prospecting with probability=1.2
00-Adir-01:344.667 (Info) MissionManager : [Schiaparelli Point] Julen Gómez - Mission Regolith Prospecting with probability=1.2
00-Adir-01:344.667 (Info) MissionManager : [Schiaparelli Point] Julen Gómez - Mission Mineral Exploration with probability=1.0
00-Adir-01:344.667 (Info) Mission : [Schiaparelli Point] Julen Gómez - Began organizing a Regolith Prospecting mission.
00-Adir-01:344.667 (Info) CollectResourcesMission : Regolith Prospecting totalSiteScore: 200.0   bestScore: 100.0
00-Adir-01:344.667 (Info) CollectResourcesMission : Regolith Prospecting totalSiteScore: 300.0   bestScore: 100.0
00-Adir-01:344.667 (Info) CollectResourcesMission : [Schiaparelli Point] Martian Cloud - Target amount of resource per site: 1333 kg of regolith.
00-Adir-01:344.667 (Info) VehicleMission : [Schiaparelli Point] Martian Cloud - 1. Regolith Prospecting #7 has an estimated remaining distance of 17.2 km.
00-Adir-01:344.667 (Info) VehicleMission : [Schiaparelli Point] Martian Cloud - Trip Distance: 17.2 km   Fuel Economy: 7.2 km/kg   Fuel Margin: 3.3   Fuel: 7.9 kg
00-Adir-01:344.667 (Info) VehicleMission : [Schiaparelli Point] Martian Cloud - Regolith Prospecting #7 has an estimated remaining trip time of 525.1 millisols.
...
00-Adir-01:384.891 (Info) BuildingManager : [Schiaparelli Point] Martian Cloud - Stowed inside Garage 1.
00-Adir-01:384.891 (Info) BuildingManager : [Schiaparelli Point] Martian Cloud - Already inside Garage 1.
00-Adir-01:384.891 (Info) VehicleMission : [Schiaparelli Point] Martian Cloud - Prepared a loading plan sourced from Schiaparelli Point.
...
00-Adir-01:402.006 (Info) Walk : [Schiaparelli Point - Martian Cloud] Margarida Oliveira - Entered rover Martian Cloud inside Garage 1.
00-Adir-01:402.859 (Info) Walk : [Schiaparelli Point - Martian Cloud] Julen Gómez - Entered rover Martian Cloud inside Garage 1.
...
00-Adir-01:415.631 (Info) Walk : [Schiaparelli Point - Martian Cloud] Sara Martín - Entered rover Martian Cloud inside Garage 1.
...
00-Adir-01:425.868 (Info) Walk : [Schiaparelli Point - Martian Cloud] Milana Kask - Entered rover Martian Cloud inside Garage 1.
...
00-Adir-01:436.100 (Info) DriveGroundVehicle : [0.00 N 0.00 W - Martian Cloud] Milana Kask - Took the wheel of the rover.
...
00-Adir-01:441.253 (Info) VehicleMission [x3] : [0.06 S 0.00 W] Martian Cloud - 1. Regolith Prospecting #7 has an estimated remaining distance of 13.8 km.
00-Adir-01:441.253 (Info) VehicleMission [x3] : [0.06 S 0.00 W] Martian Cloud - Trip Distance: 13.8 km   Fuel Economy: 7.2 km/kg   Fuel Margin: 1.0   Fuel: 1.9 kg
...
00-Adir-01:577.925 (Info) EnterAirlock : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
...
00-Adir-01:589.855 (Info) EnterAirlock [x154] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
...
00-Adir-01:601.816 (Info) EnterAirlock [x154] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
...
00-Adir-01:613.749 (Info) EnterAirlock [x154] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
...
00-Adir-01:765.809 (Info) EnterAirlock [x22] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
...
00-Adir-01:790.482 (Info) EnterAirlock [x79399] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
00-Adir-01:790.482 (Info) EnterAirlock [x182913] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
00-Adir-01:790.482 (Info) EnterAirlock [x186371] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
00-Adir-01:790.482 (Info) EnterAirlock [x185578] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
00-Adir-01:790.482 (Info) EnterAirlock [x183499] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
00-Adir-01:790.482 (Info) EnterAirlock [x181176] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
00-Adir-01:790.482 (Info) EnterAirlock [x169889] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
00-Adir-01:790.482 (Info) EnterAirlock [x172398] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
...
00-Adir-01:793.861 (Info) EnterAirlock [x135136] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
00-Adir-01:797.240 (Info) EnterAirlock [x180406] : [0.06 S 0.00 W] Sara Martín - Could not enter Martian Cloud. Already full.
...
00-Adir-01:859.561 (Info) CollectResourcesMission : [0.06 S 0.00 W - Martian Cloud] Julen Gómez - Too dark for Collecting resources at Prospecting Site #1 of Regolith Prospecting #7, moving to next site
00-Adir-01:859.561 (Info) VehicleMission : [0.06 S 0.00 W] Martian Cloud - 1. Regolith Prospecting #7 has an estimated remaining distance of 13.8 km.
00-Adir-01:859.561 (Info) VehicleMission : [0.06 S 0.00 W] Martian Cloud - Trip Distance: 13.8 km   Fuel Economy: 6.0 km/kg   Fuel Margin: 1.0   Fuel: 2.3 kg
...
00-Adir-01:913.036 (Info) EnterAirlock : [0.06 S 0.00 W] Margarida Oliveira - Could not enter Martian Cloud. Already full.
00-Adir-01:913.036 (Info) DriveGroundVehicle : [0.06 S 0.00 W - Martian Cloud] Julen Gómez - Took the wheel of the rover.
...
00-Adir-01:922.045 (Info) RoverMission : [0.07 S 0.01 E] Martian Cloud - Continue travel, sunrise too late 00-Adir-02:281
...
00-Adir-01:956.441 (Info) RoverMission : [0.12 S 0.05 W] Martian Cloud - Continue travel, sunrise too late 00-Adir-02:282
...
00-Adir-02:007.229 (Info) VehicleMission : [0.00 N 0.00 W] Martian Cloud - Arrived back home Schiaparelli Point
...
00-Adir-02:010.608 (Info) RoverMission : [Schiaparelli Point] Martian Cloud - Disembarked at Schiaparelli Point triggered by Milana Kask.
00-Adir-02:010.608 (Info) BuildingManager : [Schiaparelli Point] Martian Cloud - Stowed inside Garage 1.
00-Adir-02:010.608 (Info) BuildingManager [x6] : [Schiaparelli Point] Martian Cloud - Already inside Garage 1.
00-Adir-02:010.608 (Info) TaskManager : [Schiaparelli Point] Margarida Oliveira - Quit 'Collecting Resources' to start new Task 'Unloading Martian Cloud in Garage'.
00-Adir-02:011.577 (Info) UnloadVehicleGarage : [Schiaparelli Point] Milana Kask - Unloaded Large Bag 175 from Martian Cloud.
00-Adir-02:011.577 (Info) UnloadVehicleGarage : [Schiaparelli Point] Margarida Oliveira - Unloaded Large Bag 186 from Martian Cloud.
...
00-Adir-02:012.708 (Info) UnloadVehicleGarage : [Schiaparelli Point] Margarida Oliveira - Just unloaded 20.39 kg of resources from Martian Cloud.
...
00-Adir-02:017.794 (Info) UnloadVehicleGarage : [Schiaparelli Point] DeliveryBot 004 - Just unloaded 2.76 kg of resources from Martian Cloud.
...
00-Adir-02:019.144 (Info) UnloadVehicleGarage : [Schiaparelli Point] DeliveryBot 005 - Just unloaded 2.1 kg of resources from Martian Cloud.
...
00-Adir-02:101.016 (Info) RoverMission : [Schiaparelli Point] Martian Cloud - Disembarked at Schiaparelli Point triggered by Sara Martín.
00-Adir-02:111.686 (Info) DeliveryMeta [x3] : [Schiaparelli Point] Drone 014 available for delivery mission.
00-Adir-02:116.750 (Info) Mission : [Schiaparelli Point] Julen Gómez - Ended the Regolith Prospecting #7 with the status flag(s): Mission Accomplished
00-Adir-02:116.750 (Info) Mission : [Schiaparelli Point] Julen Gómez - Disbanded mission member(s) : [Julen Gómez, Sara Martín, Margarida Oliveira, Milana Kask]
00-Adir-02:118.584 (Info) LocationTabPanel : Martian Cloud's coordinates: 0.00 N 0.00 W   Elevation: -1.482 km.

```

**Comment by mokun** [comment] 2022-06-19 04:42
@bevans2000 

> Why in the vehicle log the key (timestamp) is there but with empty value (status type).

Can you check what went wrong with the Vehicle's status log ?

I'm trying to see if the methods below are good in Vehicle. May be the writeLog() has issues.

```
	/**
	 * Adds a status type for this vehicle
	 *
	 * @param newStatus the status to be added
	 */
	public void addStatus(StatusType newStatus) {
		// Update status based on current situation.
		if (!statusTypes.contains(newStatus)) {
			statusTypes.add(newStatus);
			writeLog();
			fireUnitUpdate(UnitEventType.STATUS_EVENT, newStatus);
		}
	}

	/**
	 * Remove a status type for this vehicle
	 *
	 * @param oldStatus the status to be removed
	 */
	public void removeStatus(StatusType oldStatus) {
		// Update status based on current situation.
		if (statusTypes.contains(oldStatus)) {
			statusTypes.remove(oldStatus);
			writeLog();
			fireUnitUpdate(UnitEventType.STATUS_EVENT, oldStatus);
		}
	}
```

**Comment by bevans2000** [comment] 2022-06-19 19:39
The problem with the blank entries is in the ```removeStatus``` method ir is emptying the status set which is then written to the log and hence creates a blank entry. The root cause is probably something wrong with a Vehicle flipping between Garaged and Parked. I've noticed there are cases where we remove a status and then immediately add a new one; we should problem have a ```replaceStatus``` method and do this as a single operation.
To address the immediate problem I will stop the ```writeLog``` method logging an entry when the status set is empry.

**Comment by bevans2000** [comment] 2022-06-19 19:52
To be honest the bigger problem here is the use of a set for Status. Really there is a primary Status that controls the vehicles situation (Parked, Garaged, Surface) and then a set of secondary statuses that argument the others. The primary status can be automatically updated based on the Location of the Vehicle and hence remove the majority of the add/remove Status calls. This is mutually exclusive as well and at least one will be defined. The Add & Remove status calls is then needed just for the secondary situation.

**Comment by bevans2000** [comment] 2022-06-20 07:50
For me the key is that some of the Status are mutually exclusive but we don't enforce it in the design, e.g. Parked, Garaged, Moving, We have a lot of logic that removes the old primary status and replaces it with a new one; each time this generates a log message.

**Comment by bevans2000** [comment] 2022-06-20 20:54
I am going to look into the Vehicle status to separate out the primary status as it will simplify the calling logic and guarantee there will always be an entry in the log.

**Comment by mokun** [comment] 2022-06-21 02:40
> I am going to look into the Vehicle status to separate out the primary status as it will simplify the calling logic and guarantee there will always be an entry in the log.

I see.

**Comment by bevans2000** [comment] 2022-06-23 22:56
I don't think it is maintenance but nevertheless it flips between garages and parked over a few pulses. I will trap it in a debugger to work backward to the cause.

**Comment by mokun** [comment] 2022-07-11 17:20
@bevans2000 

I don't see any problems with this anymore for the time being. 

Should we leave this issue open for a bit for more observation ?

**Comment by bevans2000** [comment] 2022-07-11 17:53
No let's close it. We can always create a new issue with the new symptoms

**Comment by bevans2000** [comment] 2022-11-27 18:14
I changed the logic in #754 so a Vehicle is only moved to a Garage once in the initial transition to Loading. This should reduces the flipping.

**Comment by bevans2000** [comment] 2022-12-08 08:16
There have been many changes in this are so I've closed this after fixing the Status Log last night.

**Closed** 2022-12-08 08:15 UTC
Labels: bug
