### ISSUE TITLE
Game doesn't launch; Crash after renaming alpha crew members

### ISSUE THREAD

**Issue by EmilPetecki** [mars-sim/mars-sim#191] opened 2019-04-15 02:19 UTC
**Describe the bug/issue**
 - Nothing happens when I'm trying to launch the game, all versions don't work, including 3.1.0-b1. Nothing happens when I click the jar file or the exe. The box disappears very fast but it seems to show that a JNR error has occured.

**Comment by mokun** [comment] 2019-04-15 04:49
Hi @EmilPetecki , 

Can you provide the OS platform (Windows, linux, or macOS ) that you're on and the version of Java you've installed ? 

This way we can debug and see what went wrong. 

Appreciate !

**Comment by mokun** [comment] 2019-04-15 04:50
>  all versions don't work, including 3.1.0-b1. 

Also, have you tried out Build 4925 that can be downloaded in https://github.com/mars-sim/mars-sim/releases ?

**Comment by EmilPetecki** [comment] 2019-04-16 18:10
I've tried it but it's still not working. I'm using Java 11 I found here https://www.itechtics.com/download-java-11/

**Comment by Urwumpe** [comment] 2019-04-16 18:32
First of all, that Java 11 URL is not the official download link - are you SURE that is a good idea?

Next, did you also get OpenJFX? If not, did you try a headless version already?

For all UI versions, you need OpenJFX now, because JavaFX is no longer part of the JRE.

**Comment by mokun** [comment] 2019-04-16 19:19
@EmilPetecki , if you run build 4925, there's no need of having JavaFX or OpenJFX.  

Please see the instructions at https://github.com/mars-sim/mars-sim/releases, 

build 4925 requires only Java Swing as the GUI.

After you download "r4925_gui_java11.jar", at a command prompt, type "java -jar r4925_gui_java11.jar" and it should start.

If not, can you post the screen shot here to show us what error message it gives ?

Appreciate !

**Comment by mokun** [comment] 2019-04-16 19:39
@EmilPetecki , 

Do you have multiple version of java installed ? and in what OS platform (Windows, linux, or macOS) ?

To me, I have java 8, java 9 and java 10, java 11 installed in windows. I just need to be careful what PATH variable I have set up so that it will use Java 11 only.

@Urwumpe , what OS do you use primarily these days for running mars-sim ?

**Comment by EmilPetecki** [comment] 2019-04-16 19:39
I've managed to run the game by clicking on it and even get a main game window I recall from the previous versions. Now it would just open the console and after choosing the sanbox and initial settings, it will do nothing. 

I don't know what is meant by the 'console' in the instructions. I've created a .bat file with > java -jar r4925_gui_java11.jar but it would only create an empty file named java.

I'm using Windows 11

**Comment by Urwumpe** [comment] 2019-04-16 19:45
> @Urwumpe , what OS do you use primarily these days for running mars-sim ?

Still Windows 10.

**Comment by Urwumpe** [comment] 2019-04-16 19:50
> 
> 
> I only have one version, Java 11.
> 
> I've managed to run the game by clicking on it and even get a main game window I recall from the previous versions. Now it would just open the console and after choosing the sanbox and initial settings, it will do nothing.

Yes, expected behavior without OpenJFX. You should have a runtime error there. 


> 
> I don't know what is meant by the 'console' in the instructions. I've created a .bat file with > java -jar r4925_gui_java11.jar but it would only create an empty file named java.

Yes, you should take away the leading ">" in the line. 

> 
> I'm using Windows 11

How that? Are you working for Microsoft? :D

**Comment by EmilPetecki** [comment] 2019-04-16 19:55
> 
> 
> > @Urwumpe , what OS do you use primarily these days for running mars-sim ?
> 
> Still Windows 10.

A typo. Yes, Win 10

**Comment by EmilPetecki** [comment] 2019-04-16 20:10
I've installed the OpenJFX and put it into my main Java folder. It seems that now the main screen will appear sometimes, and sometimes just gets stuck in the console mode. There are no errors.

**Comment by mokun** [comment] 2019-04-16 20:30
![sandbox mode](https://user-images.githubusercontent.com/1168584/56241866-cd054880-604b-11e9-98c9-5059d11be4bd.jpg)

**Comment by Urwumpe** [comment] 2019-04-16 20:31
> 
> 
> I've installed the OpenJFX and put it into my main Java folder. It seems that now the main screen will appear sometimes, and sometimes just gets stuck in the console mode. There are no errors.

You don't need to put it into the main java folder. Do you know where to locate the log files of MSP? They should be in `C:\Users\<your username>\.mars-sim\logs`, can you maybe look into them for errors?

**Comment by EmilPetecki** [comment] 2019-04-16 20:33
> 
> 
> After you chose the "Sandbox Mode", The "Simulation Configuration Editor" will pop up.
> 
> ![sandbox mode](https://user-images.githubusercontent.com/1168584/56241866-cd054880-604b-11e9-98c9-5059d11be4bd.jpg)

Yes, this always appear. The problem is that after clicking start the game screen will not always appear. 

This is my log:

2019-04-16T20:59:57.9 (Config) MarsProject$SimulationTask : Starting Mars Simulation Project v3.1.0-b2 - Build 4925 - 64-bit 11.0.3 - 4 CPU threads
2019-04-16T20:59:58.0 (Config) MarsProject : Please proceed to selecting the type of Game Mode in the popped-up console.
2019-04-16T20:59:58.9 (Config) SimulationConfig : Done loading all xml files.
2019-04-16T21:00:45.3 (Config) Simulation : Initiating the simulation core engine...
2019-04-16T21:00:45.6 (Config) MasterClock :    -------------------------------------------
2019-04-16T21:00:45.6 (Config) MasterClock :        Adjusted Time Ratio (TR) : 64x
2019-04-16T21:00:45.6 (Config) MasterClock :      Time between Updates (TBU) : 150.0 ms
2019-04-16T21:00:45.6 (Config) MasterClock :          Ticks Per Second (TPS) : 6.67 Hz
2019-04-16T21:00:45.6 (Config) MasterClock :    -------------------------------------------
2019-04-16T21:00:46.4 (Config) UnitManager : Robot GardenBot 001 is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:00:46.5 (Info) UnitManager : Karen Andersen is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:00:46.7 (Config) Mind : [Base Alpha] Karen Andersen took the Botanist job position.
2019-04-16T21:00:46.7 (Info) UnitManager : Emil Peterson is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:00:46.7 (Config) Mind : [Base Alpha] Emil Peterson took the Areologist job position.
2019-04-16T21:00:46.7 (Info) UnitManager : James Davis is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:00:46.7 (Config) Mind : [Base Alpha] James Davis took the Engineer job position.
2019-04-16T21:00:46.7 (Info) UnitManager : Lena LaGranda is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:00:46.7 (Config) Mind : [Base Alpha] Lena LaGranda took the Technician job position.
2019-04-16T21:00:46.7 (Config) ChainOfCommand : [Base Alpha] Emil Peterson got elected as the Commander.
2019-04-16T21:00:46.7 (Config) Simulation : Done initializing intransient data.
00-Adir-01:000.108 (Info) UnitManager :  - - - - - - - - - - - - Sol 1 - - - - - - - - - - - - 
2019-04-16T21:01:42.3 (Config) MarsProject$SimulationTask : Starting Mars Simulation Project v3.1.0-b2 - Build 4925 - 64-bit 11.0.3 - 4 CPU threads
2019-04-16T21:01:42.4 (Config) MarsProject : Please proceed to selecting the type of Game Mode in the popped-up console.
2019-04-16T21:01:43.0 (Config) SimulationConfig : Done loading all xml files.
2019-04-16T21:02:16.2 (Config) Simulation : Initiating the simulation core engine...
2019-04-16T21:02:16.6 (Config) MasterClock :    -------------------------------------------
2019-04-16T21:02:16.6 (Config) MasterClock :        Adjusted Time Ratio (TR) : 64x
2019-04-16T21:02:16.6 (Config) MasterClock :      Time between Updates (TBU) : 150.0 ms
2019-04-16T21:02:16.6 (Config) MasterClock :          Ticks Per Second (TPS) : 6.67 Hz
2019-04-16T21:02:16.6 (Config) MasterClock :    -------------------------------------------
2019-04-16T21:02:17.4 (Config) UnitManager : Robot GardenBot 001 is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:02:17.4 (Info) UnitManager : Karen Andersen is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:02:17.6 (Config) Mind : [Base Alpha] Karen Andersen took the Botanist job position.
2019-04-16T21:02:17.6 (Info) UnitManager : Emil Peterson is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:02:17.6 (Config) Mind : [Base Alpha] Emil Peterson took the Areologist job position.
2019-04-16T21:02:17.6 (Info) UnitManager : James Davis is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:02:17.6 (Config) Mind : [Base Alpha] James Davis took the Engineer job position.
2019-04-16T21:02:17.6 (Info) UnitManager : Lena LaGranda is being sent to Base Alpha since Schiaparelli Point doesn't exist.
2019-04-16T21:02:17.6 (Config) Mind : [Base Alpha] Lena LaGranda took the Technician job position.
2019-04-16T21:02:17.6 (Config) ChainOfCommand : [Base Alpha] Lena LaGranda got elected as the Commander.
2019-04-16T21:02:17.6 (Config) Simulation : Done initializing intransient data.
00-Adir-01:000.107 (Info) UnitManager :  - - - - - - - - - - - - Sol 1 - - - - - - - - - - - -

**Comment by Urwumpe** [comment] 2019-04-16 20:37
I see no issues there - can you delete the log files before you try again and post one when it fails to show the main window?

**Comment by mokun** [comment] 2019-04-16 20:38
Yes @Urwumpe and @EmilPetecki , 

From the log, the core engine is running properly.

I'm wondering why the main window won't pop up.

I've only tested it against 11.0.1 and 11.0.2 before.

Let me download jdk 11.0.3 and try.

**Comment by EmilPetecki** [comment] 2019-04-16 20:40
> 
> 
> I see no issues there - can you delete the log files before you try again and post one when it fails to show the main window?

This is from the one that failed to show the main window. Both instances from the log.

**Comment by EmilPetecki** [comment] 2019-04-16 20:43
It seems that I've found the issue. The game doesn't show anything if you rename any of the characters.

**Comment by mokun** [comment] 2019-04-16 20:48
> The game doesn't show anything if you rename any of the characters.

do you mean that you edited the people.xml file ?

**Comment by mokun** [comment] 2019-04-16 20:51
oh I see, you clicked on the "Edit Crew" button and change the name of a person.

This is a bug then. the Crew Editor is not working properly and fail to bring up the Main Window.

**Comment by EmilPetecki** [comment] 2019-04-16 20:56
I mean that in the menu that shows after opening the game, the one with the bases, I edited the crew.

It seems that the game is running now, but after saving it it seems impossible to load it. After opening the game again, I'm prompted to the console again so I'm creating another sandbox and immediately try to load the save but it seems that it just doesn't work.

**Comment by EmilPetecki** [comment] 2019-04-16 21:03
I tried to load the game, to no avail, posting the log below, and interestingly clicking 'save' afterwards simply broke the game, it froze without any mention of it in the log:

2019-04-16T21:59:36.0 (Config) MarsProject$SimulationTask : Starting Mars Simulation Project v3.1.0-b2 - Build 4925 - 64-bit 11.0.3 - 4 CPU threads
2019-04-16T21:59:36.0 (Config) MarsProject : Please proceed to selecting the type of Game Mode in the popped-up console.
2019-04-16T21:59:36.7 (Config) SimulationConfig : Done loading all xml files.
2019-04-16T21:59:50.9 (Config) Simulation : Initiating the simulation core engine...
2019-04-16T21:59:51.3 (Config) MasterClock :    -------------------------------------------
2019-04-16T21:59:51.3 (Config) MasterClock :        Adjusted Time Ratio (TR) : 64x
2019-04-16T21:59:51.3 (Config) MasterClock :      Time between Updates (TBU) : 150.0 ms
2019-04-16T21:59:51.3 (Config) MasterClock :          Ticks Per Second (TPS) : 6.67 Hz
2019-04-16T21:59:51.3 (Config) MasterClock :    -------------------------------------------
2019-04-16T21:59:52.4 (Config) UnitManager : Robot GardenBot 003 is being sent to Plymouth Base since Alpha Base doesn't exist.
2019-04-16T21:59:52.4 (Config) UnitManager : Robot MakerBot 004 is being sent to Schiaparelli Point since Alpha Base doesn't exist.
2019-04-16T21:59:52.7 (Config) Mind : [Schiaparelli Point] Karen Andersen took the Botanist job position.
2019-04-16T21:59:52.7 (Config) Mind : [Schiaparelli Point] Rik Declercq took the Areologist job position.
2019-04-16T21:59:52.7 (Config) Mind : [Schiaparelli Point] Leonardo DaVinci took the Engineer job position.
2019-04-16T21:59:52.7 (Config) Mind : [Schiaparelli Point] Lena LaGranda took the Technician job position.
2019-04-16T21:59:52.7 (Config) ChainOfCommand : [Schiaparelli Point] Leonardo DaVinci got elected as the Commander.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Patrick O'Hara took the Chemist job position.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Ralph Radske took the Biologist job position.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Rachel Heron took the Doctor job position.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Ivo Mesić took the Chef job position.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Michael Zummo took the Biologist job position.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Jeri Axberg took the Botanist job position.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Brian Donovan took the Doctor job position.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Mike Jones took the Chef job position.
2019-04-16T21:59:52.7 (Config) ChainOfCommand : [Plymouth Base] Rachel Heron got elected as the Commander.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Mike Jones took the Engineer job position.
2019-04-16T21:59:52.7 (Config) Mind : [Plymouth Base] Brian Donovan took the Technician job position.
2019-04-16T21:59:52.7 (Config) Simulation : Done initializing intransient data.
00-Adir-01:000.220 (Info) UnitManager :  - - - - - - - - - - - - Sol 1 - - - - - - - - - - - - 
00-Adir-01:000.648 (Config) AudioPlayer : Playing background music track #3 'Misty_Bog.ogg'
00-Adir-01:002.813 (Config) MasterClock : Time-ratio : 64x ==> 70x
00-Adir-01:002.813 (Config) MasterClock : Time-ratio : 70x ==> 70x
00-Adir-01:003.412 (Info) Farming : [Plymouth Base] During sampling analysis, Ivo Mesić could not find any potato tissue culture in stock and produced 0.05 kg from potato in Inflatable Greenhouse 1.
00-Adir-01:006.288 (Info) Farming : [Plymouth Base] During sampling analysis, Ivo Mesić could not find any lettuce tissue culture in stock and produced 0.05 kg from lettuce in Inflatable Greenhouse 1.
00-Adir-01:008.924 (Info) Farming : [Plymouth Base] During sampling analysis, Ralph Radske could not find any cabbage tissue culture in stock and produced 0.05 kg from cabbage in Inflatable Greenhouse 1.
00-Adir-01:009.053 (Info) LocationTabPanel : Schiaparelli Point's elevation is -0.0061 km.
00-Adir-01:011.680 (Info) Farming : [Plymouth Base] During sampling analysis, Ivo Mesić could not find any wheat tissue culture in stock and produced 0.05 kg from wheat in Inflatable Greenhouse 1.
00-Adir-01:012.519 (Info) LocationTabPanel : Plymouth Base's elevation is 0.3128 km.
00-Adir-01:014.436 (Info) Farming : [Plymouth Base] During sampling analysis, Ivo Mesić could not find any rice tissue culture in stock and produced 0.05 kg from rice in Inflatable Greenhouse 1.
00-Adir-01:017.432 (Config) MainWindow : MainWindow's loadSimulationProcess() is on AWT-EventQueue-0
00-Adir-01:017.432 (Config) MasterClock$ClockThreadTask : keepRunning : false
00-Adir-01:017.432 (Config) Simulation : Simulation's loadSimulation() is on AWT-EventQueue-0
00-Adir-01:017.432 (Config) Simulation : readFromFile() is on AWT-EventQueue-0
00-Adir-01:017.432 (Config) Simulation : Loading and processing the saved sim. Please wait...
00-Adir-01:017.432 (Config) Simulation : deserialize() is on AWT-EventQueue-0
00-Adir-01:017.432 (Config) Simulation :  --------------------------------------------------------------------
00-Adir-01:017.432 (Config) Simulation :                       Saved Simulation                               
00-Adir-01:017.432 (Config) Simulation :  --------------------------------------------------------------------
00-Adir-01:017.432 (Config) Simulation :                    Filename : game2.sim
00-Adir-01:017.432 (Config) Simulation :                        Path : C:\Users\Ignacy\.mars-sim\saved\
00-Adir-01:017.432 (Config) Simulation :                        Size : 132.3 KB
00-Adir-01:017.432 (Config) Simulation :               Made in Build : 4925
00-Adir-01:017.432 (Config) Simulation :   Current Core Engine Build : 4925
00-Adir-01:017.432 (Config) Simulation :     Martian Date/Time Stamp : 00-Adir-01:018.219
00-Adir-01:017.432 (Config) Simulation :  --------------------------------------------------------------------
00-Adir-01:017.432 (Config) Simulation :  Note : Both Builds are matched.
00-Adir-01:017.432 (Config) Simulation :   - - - - - - - - - Sol 1 (Cont') - - - - - - - - - - - 
00-Adir-01:018.219 (Config) Simulation : Done readFromFile()

**Comment by mokun** [comment] 2019-04-16 21:03
>  but after saving it it seems impossible to load it.

if it fails to load, then it would be another bug :(

I'm testing build 4933 now and fixing the Crew Editor.

After that, i'll see what happen with not being able to load a saved sim.

Appreciate much for helping us debugging this.

**Comment by EmilPetecki** [comment] 2019-04-16 21:09
It seems that the game saves the progress when using the option to load. 

In the meantime, is there a stable version I can play with java 11?

**Comment by Urwumpe** [comment] 2019-04-16 21:38
That path `C:\Users\Ignacy.mars-sim\saved` looks corrupted - maybe a \ missing there?

**Comment by EmilPetecki** [comment] 2019-04-16 21:41
It certainly looks like an \ is missing here, but I don't know how to change it. I chose folder from the folder box.

**Comment by EmilPetecki** [comment] 2019-04-17 14:43
Is there a version I can safely play? I've tried the Java 9 version but my Java 9 cannot open it.

**Comment by mokun** [comment] 2019-04-18 01:53
> Is there a version I can safely play? I've tried the Java 9 version but my Java 9 cannot open it.

In our last unofficial release of the Build 4925, we only manage to compile it into both Java 10 and Java 11. We tried compiling it under Java 8 and Java 9 but there are unresolved issues and they both fail to run.
 
I guess the consensus that we should aim at supporting Java 11 from now on :D

**Comment by mokun** [comment] 2019-06-12 22:22
@Urwumpe , I wonder if you can offer a quick fix to this issue. 

In the past when we rely on CrewEditorFX.java for validating the alpha membere name input, this issue doesn't not exist. 

A few month ago, I separated all the JavaFX codes into mar-sim-fx submodule (unused for now) and therefore had to put the old CrewEditor.java back to use. 

Unfortunately, CrewEditor doesn't have the same rigor in handling the alpha crew members' name change and MOST OF ALL it doesn't inject the new name correctly.

> Note that the original alpha member name and attributes are actually pulled from people.xml. With the crew editor, users may change those attributes prior to starting a new simulation.

**Comment by Urwumpe** [comment] 2019-06-12 22:41
Maybe I can take a look there at the CrewEditor and understand where the shortcomings are, but don't expect too much development time from me right now, I still have to finish a Inform7 adventure as university project in the next two weeks.

**Comment by mokun** [comment] 2019-07-02 15:47
@EmilPetecki, the last commit should fix the crash of the crew editor after a attribute change is made to a crew member. 

Feel free to open any new issues regarding other bugs. I'll close this thread for now.

Note that currently this `CrewEditor` doesn't offer the same level of validation as the `CrewEditorFX` that we once put together. 

But for now, it's considered good enough for the job until we rebuild the interface in JavaFX UI elements.

**Closed by mokun** 2019-07-02 15:47 UTC
Labels: bug

**Comment by mokun** [comment] 2020-08-06 23:59
Just corrected another issue with loading the alpha crew listed in crew.xml in this [commit](https://github.com/mars-sim/mars-sim/commit/d0ce26263c7dcea6bc9186ca32414bb11fc7b1ee)
