### ISSUE TITLE
Problem with country.xsd.tst

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#983] opened 2023-08-02 04:47 UTC
**Describe the bug**
- After the on-demand country's xml is implemented, this issue pops up from time to time in stacktrace
- In this case, it happens at sol1:100.029, not at the start of the sim

**Expected and unexpected behavior**
- This `FileSystemException` should be caught or avoided

**Java classes involved**
- `UserConfigurableConfig`
- `SimulationConfig`'s getBundledXML()
```java
	/**
	 * Finds the requested XML file in the bundled JAR and extracts to the xml sub-directory.
	 */
	public File getBundledXML(String filename) {
		if (filename.indexOf('.') == -1) {
			// Ne extension; assume XML
			filename = filename + XML_EXTENSION;
		}
		String fullPathName = "/" + XML_FOLDER + "/" + filename;

		File f = new File(SimulationFiles.getXMLDir(), filename);
		String checksumOldFile = null;

		File testf = new File(SimulationFiles.getXMLDir(), filename + ".tst");
		String checksumTestFile = null;
```

**Stacktrace**
```
01-Adir-01:100.029 (Info) TransportManager : A transport item launched on 01-Adir-01:100.000 : Schiaparelli Point
01-Adir-01:100.029 (Info) TransportManager : A transport item launched on 01-Adir-01:100.000 : Heritage
01-Adir-01:100.029 (Info) Resupply : [Schiaparelli Point] Preparing for the arrival of a resupply mission.
01-Adir-01:100.029 (Info) Resupply : [Heritage] Preparing for the arrival of a resupply mission.
01-Adir-01:100.029 (Severe) SimulationConfig : Problem getting bundled XML C:\Users\mkhelios\.mars-sim\xml\country\country.xsd.tst: The process cannot access the file because it is being used by another process
java.nio.file.FileSystemException: C:\Users\mkhelios\.mars-sim\xml\country\country.xsd.tst: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
	at java.base/java.nio.file.Files.copy(Files.java:3148)
	at org.mars_sim.msp.core.SimulationConfig.getBundledXML(SimulationConfig.java:885)
	at org.mars_sim.msp.core.configuration.UserConfigurableConfig.setXSDName(UserConfigurableConfig.java:91)
	at org.mars_sim.msp.core.person.PersonNameSpecConfig.<init>(PersonNameSpecConfig.java:39)
	at org.mars_sim.msp.core.structure.SettlementBuilder.<init>(SettlementBuilder.java:84)
	at org.mars_sim.msp.core.interplanetary.transport.resupply.Resupply.deliverOthers(Resupply.java:390)
	at org.mars_sim.msp.core.interplanetary.transport.resupply.Resupply.performArrival(Resupply.java:171)
	at org.mars_sim.msp.core.interplanetary.transport.Transportable.execute(Transportable.java:172)
	at org.mars_sim.msp.core.events.ScheduledEventManager.timePassing(ScheduledEventManager.java:170)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:902)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:816)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
01-Adir-01:100.029 (Info) TransportManager : A transport item launched on 01-Coan-07:100.000 : Schiaparelli Point
01-Adir-01:100.029 (Info) TransportManager : A transport item launched on 01-Coan-07:100.000 : Heritage
```

**Specifications (please complete the following information)**
- pre 3.6.0 build 8449

**Comment by mokun** [comment] 2023-08-02 04:50
@bevans2000 

Can you take a look ?

**Comment by bevans2000** [comment] 2023-08-02 05:54
Sure. Did you have the file open in an editor? Don't know why it has text file extention.

**Comment by mokun** [comment] 2023-08-02 05:58
> Did you have the file open in an editor? Don't know why it has text file extention.

No. I rarely used the editor and always use the -sandbox arg in Eclipse launcher to go straight to start the default scenario.

**Comment by mokun** [comment] 2023-08-02 06:00
This happens again : 
```
01-Adir-01:100.054 (Info) TransportManager : A transport item launched on 01-Adir-01:100.000 : Schiaparelli Point
01-Adir-01:100.054 (Info) Resupply : [Schiaparelli Point] Preparing for the arrival of a resupply mission.
01-Adir-01:100.054 (Info) TransportManager : A transport item launched on 01-Adir-01:100.000 : Heritage
01-Adir-01:100.054 (Info) Resupply : [Heritage] Preparing for the arrival of a resupply mission.
01-Adir-01:100.054 (Info) ReviewMissionPlan : [Kyocera] Mao Fukuda - Grading Ice Prospecting #2 Plan - Rels: 9, Site: 3.0, Review: 2; Subtotal: 14.0
01-Adir-01:100.054 (Info) ReviewMissionPlan : [Kyocera] Mao Fukuda - Done reviewing Hinata Wada's Ice Prospecting #2 mission plan.
01-Adir-01:100.054 (Severe) SimulationConfig : Problem getting bundled XML C:\Users\mkhelios\.mars-sim\xml\country\country.xsd.tst
java.nio.file.FileAlreadyExistsException: C:\Users\mkhelios\.mars-sim\xml\country\country.xsd.tst
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
	at java.base/java.nio.file.Files.copy(Files.java:3160)
	at org.mars_sim.msp.core.SimulationConfig.getBundledXML(SimulationConfig.java:885)
	at org.mars_sim.msp.core.configuration.UserConfigurableConfig.setXSDName(UserConfigurableConfig.java:91)
	at org.mars_sim.msp.core.person.PersonNameSpecConfig.<init>(PersonNameSpecConfig.java:39)
	at org.mars_sim.msp.core.structure.SettlementBuilder.<init>(SettlementBuilder.java:84)
	at org.mars_sim.msp.core.interplanetary.transport.resupply.Resupply.deliverOthers(Resupply.java:390)
	at org.mars_sim.msp.core.interplanetary.transport.resupply.Resupply.performArrival(Resupply.java:171)
	at org.mars_sim.msp.core.interplanetary.transport.Transportable.execute(Transportable.java:172)
	at org.mars_sim.msp.core.events.ScheduledEventManager.timePassing(ScheduledEventManager.java:170)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:902)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:816)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-01:100.054 (Info) TransportManager : A transport item launched on 01-Coan-07:100.000 : Heritage
01-Adir-01:100.054 (Info) TransportManager : A transport item launched on 01-Coan-07:100.000 : Schiaparelli Point
```

**Comment by mokun** [comment] 2023-08-02 06:02
Could be because both Heritage and Schiaparelli Point are Mars Society's settlement and both have the same set of transport items ?

```
01-Adir-01:100.054 (Info) TransportManager : A transport item launched on 01-Coan-07:100.000 : Heritage
01-Adir-01:100.054 (Info) TransportManager : A transport item launched on 01-Coan-07:100.000 : Schiaparelli Point
```

**Comment by bevans2000** [comment] 2023-08-02 06:10
Very odd. Must be related to new Person being created in a Transport mission. I'm sure there is an answer.

**Comment by mokun** [comment] 2023-08-03 09:02
If we have 2 settlements under one sponsor, then it probably have the same issue with Transport Manager.

Can you look into it ?

**Comment by bevans2000** [comment] 2023-08-03 17:20
I know what the problem is. We are not closing a file correctly and the getBundledXML method is not working effeciently. I can sort these.

**Closed** 2023-08-03 20:09 UTC
Labels: bug
