### ISSUE TITLE
Problem Starting can not find settlement_phase_2-us.xml

### ISSUE THREAD

**Issue by grimmspector** [mars-sim/mars-sim#788] opened 2023-01-03 20:53 UTC
**Describe the bug**
3.4.0 swing version, try to start for the first time, and I get a popup "Problem Starting can not find settlement_phase_2-us.xml" and when I hit OK it closes the simulation completely.

**To Reproduce (Please provide steps)**
1. Download "3.4.0_swing_java11.jar"
2. Run "3.4.0_swing_java11.jar"
3. See error "Problem Starting can not find settlement_phase_2-us.xml"

**Expected and unexpected behavior**
I expected to be able to launch the simulation, I cannot run the simulation.

**Discuss any potential problems you have and have not ruled out**
Unknown

**Java classes involved**
Unknown.

**Screenshots**
![msp-error](https://user-images.githubusercontent.com/65185497/210439475-ec686cb2-3b78-4952-ab6a-596d2c9a6bf9.png)

**Stacktrace**
No log file was generated.

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version :  Oracle Java 8u171, Oracle Java 19.0.1 (tried both of these)
 - mars-sim build version : 3.4.0 swing build 9b54c4f

**Additional context**
N/A

**Comment by bevans2000** [comment] 2023-01-03 21:39
This problem should be fixed in the 3.4.1 release that is available. Can you give that a try?

**Comment by grimmspector** [comment] 2023-01-03 22:31
Well that did get past that error at least. Now I get the splash screen and an hour glass that never ends. The console does appear to be working in the background. Not sure if this is because I'm using J19? J11 seems to be unavailable for normal download now.

**Comment by grimmspector** [comment] 2023-01-03 23:31
If I run it directly (like it's executable) without calling java or anything I get the same result, nothing gets output to my shell window, it opens it's own. Gives me this:

![image](https://user-images.githubusercontent.com/65185497/210458340-3b330696-c6aa-402f-a2e3-3ad87fdf1ed6.png)

Same as if I run it by double clicking on it in explorer. Is there another way I can run it with JDK?

**Comment by Urwumpe** [comment] 2023-01-03 23:58
That problem is caused by WebLAF, I am working on a start script to provide a workaround there, but a better solution would be fixing WebLAF.

**Comment by grimmspector** [comment] 2023-01-04 05:30
What in the world is WebLAF and how would I "fix" it?

**Comment by bevans2000** [comment] 2023-01-04 06:32
> What in the world is WebLAF and how would I "fix" it?

It's a library to render parts of the ui.

**Comment by grimmspector** [comment] 2023-01-04 14:23
Ah ... so it's a programming issue, and one that's beyond my skills. So I guess I'm SOL until you guys come up with a fix.

**Comment by bevans2000** [comment] 2023-01-04 16:53
It works on Java 11 as that was the build I used in 3.4.1 so it might be a different problem. What do you get when you try
  % java -jar 3.4.1_swing_java11.jar -cleanui
from a command prompt?
The fact your Console window is showing suggests the simulation is up and running. Do you have multiple monitors?

**Comment by grimmspector** [comment] 2023-01-04 16:59
Huh it launched without issue, lots of console log in the existing console window, using the cleanui flag.

I do have multiple monitors, but the splash screen never goes away and there's no window on another monitor when I run it without the cleanui flag.

This was on 11.

**Comment by bevans2000** [comment] 2023-01-04 17:17
OK, that makes sense. We have had problems in the past with the saved UI layout not reloading and it seems worse with multiple monitors. That is why the 'cleanui' option was added. I think if you close down and then run it without the cleanui it should then behave  🤞

**Comment by grimmspector** [comment] 2023-01-04 17:25
Hmm nope same problem ... was it because I didn't save it before exiting?

**Comment by bevans2000** [comment] 2023-01-04 18:42
@mokun can you remember what file needs deleting to clean up the ui problem? 
Otherwise just run with the cleanui

**Comment by Urwumpe** [comment] 2023-01-05 00:57
> Hmm nope same problem ... was it because I didn't save it before exiting?

Can you try it with the start-script I have included here? It fixes the start issues for me.

https://github.com/Urwumpe/mars-sim/blob/master/Launch_mars-sim.bat

**Comment by grimmspector** [comment] 2023-01-05 01:36
Welp this is also an issue:

![image](https://user-images.githubusercontent.com/65185497/210681817-581cdcb7-84e5-42f3-b60a-d96c3ff53aec.png)

**Comment by bevans2000** [comment] 2023-01-05 08:46
That's a  bug as I recreated it in my clean installation. This area has changed in a while so not sure what the problem is. 
I normally create new missions from the Console using the 'create mission' command.

**Comment by bevans2000** [comment] 2023-01-05 09:56
@mokun This problem relates to this commit 0ff3802db5acff4b6b6d24e7bf25c690b8ff11dd where you changed the MapPanel so it no longer has a default map set.

**Comment by grimmspector** [comment] 2023-01-05 13:22
Looks like with your batch file I can run the sim, it seems to have reset the sim. If I run it again without the batch though I have the same splash screen issue. I still get the null map issue either way.

**Comment by mokun** [comment] 2023-01-05 15:52
@grimmspector 

My bad. Thanks for catching the null map. 

> @mokun This problem relates to this commit [0ff3802](https://github.com/mars-sim/mars-sim/commit/0ff3802db5acff4b6b6d24e7bf25c690b8ff11dd) where you changed the MapPanel so it no longer has a default map set.

oic. Thanks for hunting this down. I'll put together a fix.

**Comment by bevans2000** [comment] 2023-01-05 17:50
> oic. Thanks for hunting this down. I'll put together a fix.

Do the fix  on the 3.4 bugfix branch and we can make a 3.4.2

**Comment by grimmspector** [comment] 2023-01-06 16:47
No worries, I just wish my java skills were up to helping you folks.

**Comment by Urwumpe** [comment] 2023-01-06 18:25
> No worries, I just wish my java skills were up to helping you folks.

What should I say? The sign on my desk says senior java developer, and I still didn't find much time actually understanding the code changes of the past 4 years or so. I am glad that I at least find the time for testing it.

If your java skills ain't what you wish for, how are your SVG and XML skills? The project could use new graphics all the time, adding more content to the simulation (like food recipes, new buildings, more diverse rovers) would be great as well. 

For example, we have the SpaceX bases by the name, but still no SpaceX lander. Many NASA rover designs could also be included, it wouldn't be unsuitable.

If we have a good graphics/assets pipeline in the project running, I am sure we can find more reasons for using graphics.

**Comment by grimmspector** [comment] 2023-01-10 19:58
XML is fine, markup is easy, I'm awful at anything art related though haha. I wish I had some artistic skills. But recipes and buildings and things that can be done in markup (or even JSON), is very doable.

**Comment by bevans2000** [comment] 2023-01-10 20:49
Yes good point @Urwumpe. Over the last year we gave put a lot of effort into the simulation being driven by the XML configurations. So you can add your own crews, reporting authority, settlement templates and scenario definitions. Eventually I'd like to expand this into your own building templates as well.
In theory it is possible now to create your own simulation setup.

**Comment by bevans2000** [comment] 2023-03-26 16:21
This is resolved as part of the Java 17 changes.

**Closed by bevans2000** 2023-03-26 16:21 UTC
Labels: bug, config
