### ISSUE TITLE
Persons returning to Settlement mid-Mission

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#786] opened 2023-01-02 18:06 UTC
**Describe the bug**
There is an odd condition where some Mission member are appearing back in the Settlement during a Mission. It has the effect that a Mission becomes stalled because it can not advance as it appears not all the Crew are on board; hence the Mission waits at an EVA phase for everyone to return.

**To Reproduce (Please provide steps)**
Not 100% reproducible but just run the simulation and an old Mission will become stalled at an EVA based phase. Check the crew and one of them will be inside a Settlement.

**Expected and unexpected behavior**
Crew members cannot return to a Settlement individually.

**Discuss any potential problems you have and have not ruled out**
Looking at the Person activities I think the problem related to the Prepare Food activity. A member starts one of these Tasks but somehow incorrectly is added to a Kitchen which means they are transferred to the Settlement. Then once the prepare food task is completed they appear as InSettlement and hence never return to the Vehicle. My guess is there is something wrong in the Meta logic as the task should not be presented to those not in a Settlement.

**Comment by bevans2000** [comment] 2023-01-02 18:51
Either a problem with the EatDrink logic or the forced Mission Departure logic.

**Comment by mokun** [comment] 2023-01-02 20:30
Do you have any screenshots ?

In what ways and exactly at what stage do you observe a person "jump" back to the settlement ?

**Comment by Urwumpe** [comment] 2023-01-02 20:37
Could it be caused by the logic to select a kitchen not caring, that somebody is related to a settlement, but outside it in a rover?

**Comment by bevans2000** [comment] 2023-01-02 21:11
At the moment I have changed the AbstractMission to trap the incorrect condition but I haven't traced it further yet. But the last active Task seems to be a EatDrink task so it is the favourite culprit at the moment.

**Comment by bevans2000** [comment] 2023-01-02 22:41
Found it, the problem looks like it is with the ```Workout``` Task. It checks the person ```isInside``` which return true when also in a Vehicle. This then moves the Person to a Exercise building. When the Person completes the Task they are now back inside their Settlement.
Just running some checks and adding Departing and Ending a mission to the Task Activity log as well.

**Comment by mokun** [comment] 2023-01-03 01:15
Thanks for tracking it down .

Is there a way to make it not happen "defensively" like this in other tasks. Or we have to look into each task manually, just in case?

**Comment by bevans2000** [comment] 2023-01-03 06:43
I have added a warning message when the condition is detected but the problem has already occurred. I'm would have thought the Walk Task to the gym should have failed.

**Comment by mokun** [comment] 2023-01-03 10:16
Can you commit the change? 

This way I can observe as well what tasks are bad.

I suppose there is no way to be defensive or to prevent it from happening automatically.

So we will need to catch up them manually.

**Comment by Urwumpe** [comment] 2023-01-03 11:03
> I suppose there is no way to be defensive or to prevent it from happening automatically.

We could maybe enforce usage of a common interface for all entities, which can be used as scope for for searching certain objects or infrastructures. And build those search functions (maybe in a special service class) up-on them. 

Another option with such special search functions would be returning a different return type for distant objects (where you can't just walk to) compared to searching things which are in walking distance, so functions that are used for moving settlers would be unable to use a result of a too broad search. 

But that all still requires some discipline and refactoring, but of course, would make it easier to catch such bugs beyond defensive programming.

**Comment by bevans2000** [comment] 2023-01-03 16:41
I'll commit what I've fixed later tonight after work (got to pay for Christmas some how)

In term of being defensive, yes we can to some extention. For the Task we can define the location scope in the meta data, e.g. inSettlemnt, inVehicle, eva etc etc. Then in the TaskManager check the selected Task matches the current situation of the Worker. We have a similar pattern already in MetaTask that defines a Person and/or Robot, minimum skills, preferred Jobs shift pattern.

**Comment by bevans2000** [comment] 2023-01-03 20:04
I think I may have found the problem and it's a rare race condition. A stale cache can get re-used which was created when the Person was in the Settlement just before they boarded a Vehicle. It's an odd one and I'm not 100% convinced it is the problem but I've managed to trap in the debugger. So I have change it so that the cache is only reused if the clock has not advanced.
To support the investigation I have added the Task name and an indicator for the location in the Console 'activity' command. I will take this back out in the future.

**Comment by bevans2000** [comment] 2023-01-03 20:09
@mokun Have you seen this problem? Sometimes when driving a persons flips between the 2 Phases without consuming any time. I found an example where one Person had record 24K activities for a single Sol whilst driving.

![Screenshot 2023-01-03 195214](https://user-images.githubusercontent.com/20720166/210433271-04d824bb-4d69-430d-944a-1d2fc990bd77.png)

**Comment by mokun** [comment] 2023-01-03 20:40
Hmm. The issue with "Avoiding Obstacle" has to do with calculating the terrain gradient (steepness). 

In the past I have wanted to rework the calculation of elevation as well as what it means to confront ground obstacles that would slow down a vehicle as it gets stuck.

But we may need to set up more cleanly defined scenarios. 

In overall, it will choose a different direction in order to avoid "obstacle" when driving a vehicle.

Also, I may have commented out the sunlight factor already to make it less likely to get stuck and need a winch to move the vehicle.

**Comment by mokun** [comment] 2023-01-03 20:41
In long run, we may model how a settlement will plan to develop a road network and pave roads with concrete, especially in the vicinity of a settlement.

**Comment by bevans2000** [comment] 2023-01-03 21:21
We need to resolve this because it is consuming time & memory holding all the activities. I don't understand the logic flipping between the two; the problem is neither consume any Task time which is why they just spin around until the driver runes out of energy.

Back on this issue there is still a weird problem, but I'm fairly sure it has something to do with Drinking Water. The Person starts the Drinking phase in a Vehicle but when they come to consume Water later in the phase they are in a Settlement. So my guess is there is a hidden Walk Task which is failing and dropping the Person in a random location in the Settlement. I've stopped a Person returning to the Settlement for food when in a Vehicle which is inside a Settlement.

**Comment by Urwumpe** [comment] 2023-01-05 08:47
I think I found another occurance, of settlers dying of suffocation while sleeping, because they were unable to enter the airlock. Some were driving on a Regolith Exploration mission and died back home in their bases. 

Three deaths on the first two sols. I would say, that is is show stopper bug, that should get fixed in the next release and deserves a higher priority.

**Comment by mokun** [comment] 2023-01-05 16:01
> settlers dying of suffocation while sleeping, because they were unable to enter the airlock. Some were driving on a Regolith Exploration mission and died back home in their bases.

So this would be a separate issue that we'll need to pin down the cause for suffocation. 

You saw when they die they are outside the airlock, right ? 

May be sometimes it would help debugging if we pinpoint the exact location in terms of his coordinates in a settlement when a person dies.

**Comment by mokun** [comment] 2023-01-05 16:06
> The Person starts the Drinking phase in a Vehicle but when they come to consume Water later in the phase they are in a Settlement.

I see that if we allow a person to carry a little bit of food on himself, it would help reducing the consumption of food in vehicle while still waiting for others to board vehicle. It prevents shortage of food during mission.

This would cut down the frequency of walking to a cafeteria in a building to look for food.

It makes sense in real world too. 

Nonetheless, I agree it's vital we sort out this drastic flipping of location (namely jumping from being inside a vehicle on mission back to inside a settlement).

**Comment by Urwumpe** [comment] 2023-01-05 16:50
> > settlers dying of suffocation while sleeping, because they were unable to enter the airlock. Some were driving on a Regolith Exploration mission and died back home in their bases.
> 
> So this would be a separate issue that we'll need to pin down the cause for suffocation.

No, its the same cause, I am sure.

I have an idea to get some more information about accidents and deaths, I'll make a new issue of it, so we can discuss it there.

**Comment by bevans2000** [comment] 2023-01-05 17:43
I wouldn't be surprised if people change location after they have died.

**Comment by mokun** [comment] 2023-01-06 05:18
> > I wouldn't be surprised if people change location after they have died.
> 
> That could get a bit metaphysical. Are they still people or cargo?

Guess someone else should be able to move or transfer the body of a dead perso from one place to another. A deceased person still need proper burial.

In what cases should a dead person be tracked ?

We kind of have some discussions on this in other threads in how we should handle dead people.

Should they still be on the settlement thread or not ?

**Comment by bevans2000** [comment] 2023-01-06 08:47
Once dead a Person is removed from the Settlement thread because they become passive. Yes the  body can be transferred and there is some logic for that.

**Closed** 2023-02-27 09:34 UTC
Labels: bug
