### ISSUE TITLE
How to model history of vehicle and EVA suit 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#405] opened 2021-07-30 04:24 UTC
**Feature Request**
How do we model the history of usage of a vehicle or an EVA suit ? 

**Describe the solution you'd like**
We may want to record
1. Vehicle
- trip history 
  -- driver/pilot (vehicle operator)
  -- distance traveled
  -- malfunction
  -- subsystem performance
- customization
- maintenance and repair history

2. EVA Suit
- ownership
- usage duration 
- specs
- customization
- maintenance and repair history

**Additional context**
- While we already have standard specs for each type of vehicle, we could allow customization to each of them 
- We can model temperature, pressure and heat transfer within the EVA suit, just like inside a settlement. 
- We can set up performance specs for each EVA Suit, other than its basic usage of storing O2 and water to the user.

**Comment by mokun** [comment] 2021-07-30 04:27
This [commit](https://github.com/mars-sim/mars-sim/commit/f7954fb28bba1e189b94d9849d98707eb2bfa050) allows finding an EVAsuit previously worn by the same person, thus making an EVA suit a little more personal but no more unless we start to define each EVA suit to be uniquely different from others.

**Comment by mokun** [comment] 2021-08-02 01:52
Below is a pic about Toyota Mirai's hydrogen fuel tank. It is carbon-fiber-reinforced.
![image](https://user-images.githubusercontent.com/1168584/127794123-102ac10a-e652-4553-b062-9a39e5adeb19.png)

**Comment by mokun** [comment] 2023-04-08 18:39
@bevans2000 

It's a great features to look into the history of a vehicle or an EVA suit.

Earlier I was working on the role change at https://github.com/mars-sim/mars-sim/issues/281.

It dawns on me that we could create a common class to record changes that can be applied to many aspects of changes that we are interested in looking back.

For instance, this common class may even be used for recording the changes of a settlement's raw resources.

We could even let player highlight certain changes he's interested in tracking, thus allowing the option of turning on and turning off the recording of changes.

But in the beginning, I'm good with just being able to handle the recording of a person's job/role change, and then perhaps a vehicle and EVA's repair/maintenance history.

**Comment by bevans2000** [comment] 2023-06-30 08:43
Duplicate of #888

**Comment by mokun** [comment] 2023-06-30 16:59
> Duplicate of #888

Yay we can use the History class to record certain vehicle's statistics right now, can't we ? 

Can you demonstrate ?

**Closed** 2023-07-16 19:10 UTC
Labels: improvement, feature request
